/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as auth from "../auth.js";
import type * as bookingConfirmation from "../bookingConfirmation.js";
import type * as bookingSettings from "../bookingSettings.js";
import type * as crons from "../crons.js";
import type * as customInvoices from "../customInvoices.js";
import type * as deliverablesEmail from "../deliverablesEmail.js";
import type * as deliverablesReviewEmail from "../deliverablesReviewEmail.js";
import type * as devSeed from "../devSeed.js";
import type * as drive from "../drive.js";
import type * as editInvoices from "../editInvoices.js";
import type * as editInvoicing from "../editInvoicing.js";
import type * as employeeInvitations from "../employeeInvitations.js";
import type * as employees from "../employees.js";
import type * as env from "../env.js";
import type * as feedback from "../feedback.js";
import type * as googleCalendar from "../googleCalendar.js";
import type * as http from "../http.js";
import type * as invoices from "../invoices.js";
import type * as lib_adminSearch_adminListSearchPage from "../lib/adminSearch/adminListSearchPage.js";
import type * as lib_adminSearch_adminSearchBlob from "../lib/adminSearch/adminSearchBlob.js";
import type * as lib_adminSearch_adminSearchDateParse from "../lib/adminSearch/adminSearchDateParse.js";
import type * as lib_adminSearch_adminSearchPrefixFilters from "../lib/adminSearch/adminSearchPrefixFilters.js";
import type * as lib_adminSearch_adminSearchQuery from "../lib/adminSearch/adminSearchQuery.js";
import type * as lib_archiveState from "../lib/archiveState.js";
import type * as lib_auth from "../lib/auth.js";
import type * as lib_booking_bookingAddonQuantities from "../lib/booking/bookingAddonQuantities.js";
import type * as lib_booking_bookingConfirmationActionBoundaries from "../lib/booking/bookingConfirmationActionBoundaries.js";
import type * as lib_booking_bookingConfirmationClaim from "../lib/booking/bookingConfirmationClaim.js";
import type * as lib_booking_bookingConfirmationSave from "../lib/booking/bookingConfirmationSave.js";
import type * as lib_booking_bookingConfirmationSessionPatches from "../lib/booking/bookingConfirmationSessionPatches.js";
import type * as lib_booking_bookingFormFields from "../lib/booking/bookingFormFields.js";
import type * as lib_booking_bookingInvoicePdfRender from "../lib/booking/bookingInvoicePdfRender.js";
import type * as lib_booking_bookingReceipt from "../lib/booking/bookingReceipt.js";
import type * as lib_booking_bookingReceiptEmailPipeline from "../lib/booking/bookingReceiptEmailPipeline.js";
import type * as lib_booking_bookingSettings from "../lib/booking/bookingSettings.js";
import type * as lib_booking_bookingSubmission from "../lib/booking/bookingSubmission.js";
import type * as lib_clerkInvitations from "../lib/clerkInvitations.js";
import type * as lib_contactNormalization from "../lib/contactNormalization.js";
import type * as lib_crypto_bytesToHex from "../lib/crypto/bytesToHex.js";
import type * as lib_drive_driveBookingDriveClient from "../lib/drive/driveBookingDriveClient.js";
import type * as lib_drive_driveClientAccess from "../lib/drive/driveClientAccess.js";
import type * as lib_drive_driveEditor from "../lib/drive/driveEditor.js";
import type * as lib_drive_driveFolderTreeValidation from "../lib/drive/driveFolderTreeValidation.js";
import type * as lib_drive_driveFolders from "../lib/drive/driveFolders.js";
import type * as lib_drive_driveLookup from "../lib/drive/driveLookup.js";
import type * as lib_drive_driveScheduling from "../lib/drive/driveScheduling.js";
import type * as lib_drive_driveSetupLoad from "../lib/drive/driveSetupLoad.js";
import type * as lib_drive_driveStatus from "../lib/drive/driveStatus.js";
import type * as lib_drive_editorRetirement from "../lib/drive/editorRetirement.js";
import type * as lib_drive_googleDrive from "../lib/drive/googleDrive.js";
import type * as lib_drive_sessionFolders_allocateNumbers from "../lib/drive/sessionFolders/allocateNumbers.js";
import type * as lib_drive_sessionFolders_cancelCleanup from "../lib/drive/sessionFolders/cancelCleanup.js";
import type * as lib_drive_sessionFolders_clearSessionRecords from "../lib/drive/sessionFolders/clearSessionRecords.js";
import type * as lib_drive_sessionFolders_driveSetupInfo from "../lib/drive/sessionFolders/driveSetupInfo.js";
import type * as lib_drive_sessionFolders_resolveFolderNames from "../lib/drive/sessionFolders/resolveFolderNames.js";
import type * as lib_editor_deliverablesReviewNotification from "../lib/editor/deliverablesReviewNotification.js";
import type * as lib_editor_editorAccess from "../lib/editor/editorAccess.js";
import type * as lib_editor_editorAssignments from "../lib/editor/editorAssignments.js";
import type * as lib_editor_editorSessions from "../lib/editor/editorSessions.js";
import type * as lib_email_emailDomain from "../lib/email/emailDomain.js";
import type * as lib_email_emailRenders from "../lib/email/emailRenders.js";
import type * as lib_email_emailSend from "../lib/email/emailSend.js";
import type * as lib_feedback from "../lib/feedback.js";
import type * as lib_googleCalendar_googleAuth from "../lib/googleCalendar/googleAuth.js";
import type * as lib_googleCalendar_googleCalendarAvailability from "../lib/googleCalendar/googleCalendarAvailability.js";
import type * as lib_googleCalendar_googleCalendarClient from "../lib/googleCalendar/googleCalendarClient.js";
import type * as lib_googleCalendar_googleCalendarErrors from "../lib/googleCalendar/googleCalendarErrors.js";
import type * as lib_googleCalendar_googleCalendarEventCalls from "../lib/googleCalendar/googleCalendarEventCalls.js";
import type * as lib_googleCalendar_packageCalendarDetails from "../lib/googleCalendar/packageCalendarDetails.js";
import type * as lib_listAdminPackages from "../lib/listAdminPackages.js";
import type * as lib_listAdminSessions from "../lib/listAdminSessions.js";
import type * as lib_packages_packageAdjustmentInvoicePayment from "../lib/packages/packageAdjustmentInvoicePayment.js";
import type * as lib_packages_packageAdjustmentJobs from "../lib/packages/packageAdjustmentJobs.js";
import type * as lib_packages_packageAdjustmentScheduling from "../lib/packages/packageAdjustmentScheduling.js";
import type * as lib_packages_packageAdjustments from "../lib/packages/packageAdjustments.js";
import type * as lib_packages_packageArchive from "../lib/packages/packageArchive.js";
import type * as lib_packages_packageBookingsReceiptSync from "../lib/packages/packageBookingsReceiptSync.js";
import type * as lib_packages_packageCheckout from "../lib/packages/packageCheckout.js";
import type * as lib_packages_packageCheckoutClaim from "../lib/packages/packageCheckoutClaim.js";
import type * as lib_packages_packageLookup from "../lib/packages/packageLookup.js";
import type * as lib_packages_packagePaidLifecycle from "../lib/packages/packagePaidLifecycle.js";
import type * as lib_packages_packagePayment from "../lib/packages/packagePayment.js";
import type * as lib_packages_packageReminderDb from "../lib/packages/packageReminderDb.js";
import type * as lib_packages_packageReminders from "../lib/packages/packageReminders.js";
import type * as lib_packages_packageScheduling from "../lib/packages/packageScheduling.js";
import type * as lib_packages_packageSchedulingActionBoundaries from "../lib/packages/packageSchedulingActionBoundaries.js";
import type * as lib_packages_packageSessionBookings from "../lib/packages/packageSessionBookings.js";
import type * as lib_packages_packageSessionCapacity from "../lib/packages/packageSessionCapacity.js";
import type * as lib_packages_packageTokenView from "../lib/packages/packageTokenView.js";
import type * as lib_packages_packageUpdates from "../lib/packages/packageUpdates.js";
import type * as lib_rateLimits from "../lib/rateLimits.js";
import type * as lib_reminderScheduleTime from "../lib/reminderScheduleTime.js";
import type * as lib_result from "../lib/result.js";
import type * as lib_sessions_pendingCheckoutSession from "../lib/sessions/pendingCheckoutSession.js";
import type * as lib_sessions_sessionAdminEdit from "../lib/sessions/sessionAdminEdit.js";
import type * as lib_sessions_sessionArchive from "../lib/sessions/sessionArchive.js";
import type * as lib_sessions_sessionCalendarActionBoundaries from "../lib/sessions/sessionCalendarActionBoundaries.js";
import type * as lib_sessions_sessionCalendarEventPayload from "../lib/sessions/sessionCalendarEventPayload.js";
import type * as lib_sessions_sessionCalendarTime from "../lib/sessions/sessionCalendarTime.js";
import type * as lib_sessions_sessionCheckout from "../lib/sessions/sessionCheckout.js";
import type * as lib_sessions_sessionLookup from "../lib/sessions/sessionLookup.js";
import type * as lib_sessions_sessionReminderDb from "../lib/sessions/sessionReminderDb.js";
import type * as lib_sessions_sessionRescheduleLinks from "../lib/sessions/sessionRescheduleLinks.js";
import type * as lib_sessions_sessionReservationDb from "../lib/sessions/sessionReservationDb.js";
import type * as lib_sessions_sessionReservations from "../lib/sessions/sessionReservations.js";
import type * as lib_sessions_sessionSavePatch from "../lib/sessions/sessionSavePatch.js";
import type * as lib_sessions_sessionSchedulingArgs from "../lib/sessions/sessionSchedulingArgs.js";
import type * as lib_sessions_sessionSchedulingSave from "../lib/sessions/sessionSchedulingSave.js";
import type * as lib_sessions_sessionSlotReservationAction from "../lib/sessions/sessionSlotReservationAction.js";
import type * as lib_stripe_customInvoices from "../lib/stripe/customInvoices.js";
import type * as lib_stripe_editInvoiceBilling from "../lib/stripe/editInvoiceBilling.js";
import type * as lib_stripe_editInvoiceDb from "../lib/stripe/editInvoiceDb.js";
import type * as lib_stripe_editInvoiceLineItems from "../lib/stripe/editInvoiceLineItems.js";
import type * as lib_stripe_editInvoiceRequest from "../lib/stripe/editInvoiceRequest.js";
import type * as lib_stripe_editInvoiceStripe from "../lib/stripe/editInvoiceStripe.js";
import type * as lib_stripe_invoiceDownloads from "../lib/stripe/invoiceDownloads.js";
import type * as lib_stripe_stripeAdjustmentInvoice from "../lib/stripe/stripeAdjustmentInvoice.js";
import type * as lib_stripe_stripeApiErrors from "../lib/stripe/stripeApiErrors.js";
import type * as lib_stripe_stripeCheckoutSession from "../lib/stripe/stripeCheckoutSession.js";
import type * as lib_stripe_stripeClient from "../lib/stripe/stripeClient.js";
import type * as lib_stripe_stripeInvoice from "../lib/stripe/stripeInvoice.js";
import type * as lib_stripe_stripeInvoiceBillingUrls from "../lib/stripe/stripeInvoiceBillingUrls.js";
import type * as lib_stripe_stripeInvoices from "../lib/stripe/stripeInvoices.js";
import type * as lib_tests_testIds from "../lib/tests/testIds.js";
import type * as packageAdjustmentInvoices from "../packageAdjustmentInvoices.js";
import type * as packageAdjustments from "../packageAdjustments.js";
import type * as packageCheckout from "../packageCheckout.js";
import type * as packageCheckoutCompletionHandlers from "../packageCheckoutCompletionHandlers.js";
import type * as packagePayment from "../packagePayment.js";
import type * as packageReminders from "../packageReminders.js";
import type * as packageScheduling from "../packageScheduling.js";
import type * as packageSchedulingCalendar from "../packageSchedulingCalendar.js";
import type * as packages from "../packages.js";
import type * as receiptEmails from "../receiptEmails.js";
import type * as services_auth from "../services/auth.js";
import type * as services_authPermissions from "../services/authPermissions.js";
import type * as services_booking_bookingClaimedSession from "../services/booking/bookingClaimedSession.js";
import type * as services_booking_bookingConfirmation from "../services/booking/bookingConfirmation.js";
import type * as services_booking_bookingConfirmationMutations from "../services/booking/bookingConfirmationMutations.js";
import type * as services_booking_bookingConfirmationWorkflow from "../services/booking/bookingConfirmationWorkflow.js";
import type * as services_booking_bookingFormValidators from "../services/booking/bookingFormValidators.js";
import type * as services_booking_bookingReceiptEmails from "../services/booking/bookingReceiptEmails.js";
import type * as services_booking_bookingReceiptResend from "../services/booking/bookingReceiptResend.js";
import type * as services_booking_bookingSettings from "../services/booking/bookingSettings.js";
import type * as services_booking_bookingSubmission from "../services/booking/bookingSubmission.js";
import type * as services_booking_sessionCheckout from "../services/booking/sessionCheckout.js";
import type * as services_booking_sessionReminderEmail from "../services/booking/sessionReminderEmail.js";
import type * as services_drive_cleanupCancelledSessionDrive from "../services/drive/cleanupCancelledSessionDrive.js";
import type * as services_drive_clientDrivePermissions from "../services/drive/clientDrivePermissions.js";
import type * as services_drive_drive from "../services/drive/drive.js";
import type * as services_drive_driveClientPermissions from "../services/drive/driveClientPermissions.js";
import type * as services_drive_driveEditorPermissions from "../services/drive/driveEditorPermissions.js";
import type * as services_drive_driveInternal from "../services/drive/driveInternal.js";
import type * as services_drive_driveInternalClientAccess from "../services/drive/driveInternalClientAccess.js";
import type * as services_drive_driveInternalEditor from "../services/drive/driveInternalEditor.js";
import type * as services_drive_driveSetupQuery from "../services/drive/driveSetupQuery.js";
import type * as services_drive_driveStatusQuery from "../services/drive/driveStatusQuery.js";
import type * as services_drive_editorDrivePermissions from "../services/drive/editorDrivePermissions.js";
import type * as services_drive_editorRetirement from "../services/drive/editorRetirement.js";
import type * as services_drive_ensureSessionDriveFolderClientSteps from "../services/drive/ensureSessionDriveFolderClientSteps.js";
import type * as services_drive_ensureSessionDriveFolderHelpers from "../services/drive/ensureSessionDriveFolderHelpers.js";
import type * as services_drive_ensureSessionDriveFolderSessionSteps from "../services/drive/ensureSessionDriveFolderSessionSteps.js";
import type * as services_drive_ensureSessionDriveFolderSteps from "../services/drive/ensureSessionDriveFolderSteps.js";
import type * as services_drive_ensureSessionDriveFolders from "../services/drive/ensureSessionDriveFolders.js";
import type * as services_drive_googleDriveFolderTree from "../services/drive/googleDriveFolderTree.js";
import type * as services_editor_deliverablesEmail from "../services/editor/deliverablesEmail.js";
import type * as services_editor_deliverablesReviewReadyEmail from "../services/editor/deliverablesReviewReadyEmail.js";
import type * as services_editor_loadSessionForDeliverables from "../services/editor/loadSessionForDeliverables.js";
import type * as services_editor_sessionEditStatus from "../services/editor/sessionEditStatus.js";
import type * as services_email_bookingCustomerEmails from "../services/email/bookingCustomerEmails.js";
import type * as services_email_hostBookingEmails from "../services/email/hostBookingEmails.js";
import type * as services_email_packageReminderEmails from "../services/email/packageReminderEmails.js";
import type * as services_email_templateEmails from "../services/email/templateEmails.js";
import type * as services_employees_employeeInvitation from "../services/employees/employeeInvitation.js";
import type * as services_employees_employeeManagement from "../services/employees/employeeManagement.js";
import type * as services_feedback_feedbackEmail from "../services/feedback/feedbackEmail.js";
import type * as services_feedback_submitFeedback from "../services/feedback/submitFeedback.js";
import type * as services_googleCalendar_cancelBookingFromAdmin from "../services/googleCalendar/cancelBookingFromAdmin.js";
import type * as services_googleCalendar_packageCalendarAvailability from "../services/googleCalendar/packageCalendarAvailability.js";
import type * as services_googleCalendar_packageCalendarDetails from "../services/googleCalendar/packageCalendarDetails.js";
import type * as services_googleCalendar_packageSchedulingCalendar from "../services/googleCalendar/packageSchedulingCalendar.js";
import type * as services_googleCalendar_sessionAdminUpdate from "../services/googleCalendar/sessionAdminUpdate.js";
import type * as services_googleCalendar_sessionCalendar from "../services/googleCalendar/sessionCalendar.js";
import type * as services_googleCalendar_sessionCalendarAvailability from "../services/googleCalendar/sessionCalendarAvailability.js";
import type * as services_googleCalendar_sessionCalendarAvailabilityLoad from "../services/googleCalendar/sessionCalendarAvailabilityLoad.js";
import type * as services_googleCalendar_sessionCalendarEvent from "../services/googleCalendar/sessionCalendarEvent.js";
import type * as services_googleCalendar_sessionCalendarEventOrchestrationSteps from "../services/googleCalendar/sessionCalendarEventOrchestrationSteps.js";
import type * as services_googleCalendar_sessionCalendarReschedule from "../services/googleCalendar/sessionCalendarReschedule.js";
import type * as services_googleCalendar_sessionCalendarTime from "../services/googleCalendar/sessionCalendarTime.js";
import type * as services_googleCalendar_sessionCalendarTimingSync from "../services/googleCalendar/sessionCalendarTimingSync.js";
import type * as services_packages_claimedPackageCheckoutCompletion from "../services/packages/claimedPackageCheckoutCompletion.js";
import type * as services_packages_packageAdjustmentCron from "../services/packages/packageAdjustmentCron.js";
import type * as services_packages_packageAdjustmentInvoiceEmail from "../services/packages/packageAdjustmentInvoiceEmail.js";
import type * as services_packages_packageAdjustmentInvoicePayment from "../services/packages/packageAdjustmentInvoicePayment.js";
import type * as services_packages_packageAdjustmentInvoiceSend from "../services/packages/packageAdjustmentInvoiceSend.js";
import type * as services_packages_packageAdjustments from "../services/packages/packageAdjustments.js";
import type * as services_packages_packageAdminMutations from "../services/packages/packageAdminMutations.js";
import type * as services_packages_packageAdminQueries from "../services/packages/packageAdminQueries.js";
import type * as services_packages_packageArchive from "../services/packages/packageArchive.js";
import type * as services_packages_packageBookingsReceiptSync from "../services/packages/packageBookingsReceiptSync.js";
import type * as services_packages_packageCheckoutCompletion from "../services/packages/packageCheckoutCompletion.js";
import type * as services_packages_packageCheckoutMutations from "../services/packages/packageCheckoutMutations.js";
import type * as services_packages_packageCheckoutSession from "../services/packages/packageCheckoutSession.js";
import type * as services_packages_packageInternalMutations from "../services/packages/packageInternalMutations.js";
import type * as services_packages_packageLookup from "../services/packages/packageLookup.js";
import type * as services_packages_packagePaidEmailResend from "../services/packages/packagePaidEmailResend.js";
import type * as services_packages_packagePaidEmailSend from "../services/packages/packagePaidEmailSend.js";
import type * as services_packages_packageReminderMutations from "../services/packages/packageReminderMutations.js";
import type * as services_packages_packageReminders from "../services/packages/packageReminders.js";
import type * as services_packages_packageSessionCancel from "../services/packages/packageSessionCancel.js";
import type * as services_packages_packageSessionMutations from "../services/packages/packageSessionMutations.js";
import type * as services_packages_packageSessionScheduling from "../services/packages/packageSessionScheduling.js";
import type * as services_packages_packageSessionSchedulingTypes from "../services/packages/packageSessionSchedulingTypes.js";
import type * as services_packages_packageTokenScheduling from "../services/packages/packageTokenScheduling.js";
import type * as services_requirePermissionActions from "../services/requirePermissionActions.js";
import type * as services_sessions_sessionArchive from "../services/sessions/sessionArchive.js";
import type * as services_sessions_sessionDeliverables from "../services/sessions/sessionDeliverables.js";
import type * as services_sessions_sessionEditorAssignment from "../services/sessions/sessionEditorAssignment.js";
import type * as services_sessions_sessionLookup from "../services/sessions/sessionLookup.js";
import type * as services_sessions_sessionMutations from "../services/sessions/sessionMutations.js";
import type * as services_sessions_sessionQueries from "../services/sessions/sessionQueries.js";
import type * as services_sessions_sessionReminderCron from "../services/sessions/sessionReminderCron.js";
import type * as services_sessions_sessionReminderMutations from "../services/sessions/sessionReminderMutations.js";
import type * as services_sessions_sessionReschedule from "../services/sessions/sessionReschedule.js";
import type * as services_sessions_sessionRescheduleEmails from "../services/sessions/sessionRescheduleEmails.js";
import type * as services_sessions_sessionReservationValidators from "../services/sessions/sessionReservationValidators.js";
import type * as services_sessions_sessionReservations from "../services/sessions/sessionReservations.js";
import type * as services_sessions_sessionSchedulingSave from "../services/sessions/sessionSchedulingSave.js";
import type * as services_sessions_sessions from "../services/sessions/sessions.js";
import type * as services_sessions_sessionsEditor from "../services/sessions/sessionsEditor.js";
import type * as services_stripe_bookingCustomInvoice from "../services/stripe/bookingCustomInvoice.js";
import type * as services_stripe_editInvoiceBilling from "../services/stripe/editInvoiceBilling.js";
import type * as services_stripe_editInvoiceSend from "../services/stripe/editInvoiceSend.js";
import type * as services_stripe_editInvoiceValidators from "../services/stripe/editInvoiceValidators.js";
import type * as services_stripe_invoicePdf from "../services/stripe/invoicePdf.js";
import type * as services_stripe_stripeCheckoutSession from "../services/stripe/stripeCheckoutSession.js";
import type * as services_stripe_stripeInvoiceMutations from "../services/stripe/stripeInvoiceMutations.js";
import type * as services_stripe_stripeInvoicePayment from "../services/stripe/stripeInvoicePayment.js";
import type * as services_stripe_stripeInvoiceSend from "../services/stripe/stripeInvoiceSend.js";
import type * as services_stripe_stripeInvoices from "../services/stripe/stripeInvoices.js";
import type * as sessionCheckout from "../sessionCheckout.js";
import type * as sessionReminders from "../sessionReminders.js";
import type * as sessionReschedule from "../sessionReschedule.js";
import type * as sessionScheduling from "../sessionScheduling.js";
import type * as sessions from "../sessions.js";
import type * as sessionsDriveInternal from "../sessionsDriveInternal.js";
import type * as stripe from "../stripe.js";
import type * as stripeInvoices from "../stripeInvoices.js";
import type * as stripeInvoicing from "../stripeInvoicing.js";
import type * as tests_insertDocumentDefaults from "../tests/insertDocumentDefaults.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  auth: typeof auth;
  bookingConfirmation: typeof bookingConfirmation;
  bookingSettings: typeof bookingSettings;
  crons: typeof crons;
  customInvoices: typeof customInvoices;
  deliverablesEmail: typeof deliverablesEmail;
  deliverablesReviewEmail: typeof deliverablesReviewEmail;
  devSeed: typeof devSeed;
  drive: typeof drive;
  editInvoices: typeof editInvoices;
  editInvoicing: typeof editInvoicing;
  employeeInvitations: typeof employeeInvitations;
  employees: typeof employees;
  env: typeof env;
  feedback: typeof feedback;
  googleCalendar: typeof googleCalendar;
  http: typeof http;
  invoices: typeof invoices;
  "lib/adminSearch/adminListSearchPage": typeof lib_adminSearch_adminListSearchPage;
  "lib/adminSearch/adminSearchBlob": typeof lib_adminSearch_adminSearchBlob;
  "lib/adminSearch/adminSearchDateParse": typeof lib_adminSearch_adminSearchDateParse;
  "lib/adminSearch/adminSearchPrefixFilters": typeof lib_adminSearch_adminSearchPrefixFilters;
  "lib/adminSearch/adminSearchQuery": typeof lib_adminSearch_adminSearchQuery;
  "lib/archiveState": typeof lib_archiveState;
  "lib/auth": typeof lib_auth;
  "lib/booking/bookingAddonQuantities": typeof lib_booking_bookingAddonQuantities;
  "lib/booking/bookingConfirmationActionBoundaries": typeof lib_booking_bookingConfirmationActionBoundaries;
  "lib/booking/bookingConfirmationClaim": typeof lib_booking_bookingConfirmationClaim;
  "lib/booking/bookingConfirmationSave": typeof lib_booking_bookingConfirmationSave;
  "lib/booking/bookingConfirmationSessionPatches": typeof lib_booking_bookingConfirmationSessionPatches;
  "lib/booking/bookingFormFields": typeof lib_booking_bookingFormFields;
  "lib/booking/bookingInvoicePdfRender": typeof lib_booking_bookingInvoicePdfRender;
  "lib/booking/bookingReceipt": typeof lib_booking_bookingReceipt;
  "lib/booking/bookingReceiptEmailPipeline": typeof lib_booking_bookingReceiptEmailPipeline;
  "lib/booking/bookingSettings": typeof lib_booking_bookingSettings;
  "lib/booking/bookingSubmission": typeof lib_booking_bookingSubmission;
  "lib/clerkInvitations": typeof lib_clerkInvitations;
  "lib/contactNormalization": typeof lib_contactNormalization;
  "lib/crypto/bytesToHex": typeof lib_crypto_bytesToHex;
  "lib/drive/driveBookingDriveClient": typeof lib_drive_driveBookingDriveClient;
  "lib/drive/driveClientAccess": typeof lib_drive_driveClientAccess;
  "lib/drive/driveEditor": typeof lib_drive_driveEditor;
  "lib/drive/driveFolderTreeValidation": typeof lib_drive_driveFolderTreeValidation;
  "lib/drive/driveFolders": typeof lib_drive_driveFolders;
  "lib/drive/driveLookup": typeof lib_drive_driveLookup;
  "lib/drive/driveScheduling": typeof lib_drive_driveScheduling;
  "lib/drive/driveSetupLoad": typeof lib_drive_driveSetupLoad;
  "lib/drive/driveStatus": typeof lib_drive_driveStatus;
  "lib/drive/editorRetirement": typeof lib_drive_editorRetirement;
  "lib/drive/googleDrive": typeof lib_drive_googleDrive;
  "lib/drive/sessionFolders/allocateNumbers": typeof lib_drive_sessionFolders_allocateNumbers;
  "lib/drive/sessionFolders/cancelCleanup": typeof lib_drive_sessionFolders_cancelCleanup;
  "lib/drive/sessionFolders/clearSessionRecords": typeof lib_drive_sessionFolders_clearSessionRecords;
  "lib/drive/sessionFolders/driveSetupInfo": typeof lib_drive_sessionFolders_driveSetupInfo;
  "lib/drive/sessionFolders/resolveFolderNames": typeof lib_drive_sessionFolders_resolveFolderNames;
  "lib/editor/deliverablesReviewNotification": typeof lib_editor_deliverablesReviewNotification;
  "lib/editor/editorAccess": typeof lib_editor_editorAccess;
  "lib/editor/editorAssignments": typeof lib_editor_editorAssignments;
  "lib/editor/editorSessions": typeof lib_editor_editorSessions;
  "lib/email/emailDomain": typeof lib_email_emailDomain;
  "lib/email/emailRenders": typeof lib_email_emailRenders;
  "lib/email/emailSend": typeof lib_email_emailSend;
  "lib/feedback": typeof lib_feedback;
  "lib/googleCalendar/googleAuth": typeof lib_googleCalendar_googleAuth;
  "lib/googleCalendar/googleCalendarAvailability": typeof lib_googleCalendar_googleCalendarAvailability;
  "lib/googleCalendar/googleCalendarClient": typeof lib_googleCalendar_googleCalendarClient;
  "lib/googleCalendar/googleCalendarErrors": typeof lib_googleCalendar_googleCalendarErrors;
  "lib/googleCalendar/googleCalendarEventCalls": typeof lib_googleCalendar_googleCalendarEventCalls;
  "lib/googleCalendar/packageCalendarDetails": typeof lib_googleCalendar_packageCalendarDetails;
  "lib/listAdminPackages": typeof lib_listAdminPackages;
  "lib/listAdminSessions": typeof lib_listAdminSessions;
  "lib/packages/packageAdjustmentInvoicePayment": typeof lib_packages_packageAdjustmentInvoicePayment;
  "lib/packages/packageAdjustmentJobs": typeof lib_packages_packageAdjustmentJobs;
  "lib/packages/packageAdjustmentScheduling": typeof lib_packages_packageAdjustmentScheduling;
  "lib/packages/packageAdjustments": typeof lib_packages_packageAdjustments;
  "lib/packages/packageArchive": typeof lib_packages_packageArchive;
  "lib/packages/packageBookingsReceiptSync": typeof lib_packages_packageBookingsReceiptSync;
  "lib/packages/packageCheckout": typeof lib_packages_packageCheckout;
  "lib/packages/packageCheckoutClaim": typeof lib_packages_packageCheckoutClaim;
  "lib/packages/packageLookup": typeof lib_packages_packageLookup;
  "lib/packages/packagePaidLifecycle": typeof lib_packages_packagePaidLifecycle;
  "lib/packages/packagePayment": typeof lib_packages_packagePayment;
  "lib/packages/packageReminderDb": typeof lib_packages_packageReminderDb;
  "lib/packages/packageReminders": typeof lib_packages_packageReminders;
  "lib/packages/packageScheduling": typeof lib_packages_packageScheduling;
  "lib/packages/packageSchedulingActionBoundaries": typeof lib_packages_packageSchedulingActionBoundaries;
  "lib/packages/packageSessionBookings": typeof lib_packages_packageSessionBookings;
  "lib/packages/packageSessionCapacity": typeof lib_packages_packageSessionCapacity;
  "lib/packages/packageTokenView": typeof lib_packages_packageTokenView;
  "lib/packages/packageUpdates": typeof lib_packages_packageUpdates;
  "lib/rateLimits": typeof lib_rateLimits;
  "lib/reminderScheduleTime": typeof lib_reminderScheduleTime;
  "lib/result": typeof lib_result;
  "lib/sessions/pendingCheckoutSession": typeof lib_sessions_pendingCheckoutSession;
  "lib/sessions/sessionAdminEdit": typeof lib_sessions_sessionAdminEdit;
  "lib/sessions/sessionArchive": typeof lib_sessions_sessionArchive;
  "lib/sessions/sessionCalendarActionBoundaries": typeof lib_sessions_sessionCalendarActionBoundaries;
  "lib/sessions/sessionCalendarEventPayload": typeof lib_sessions_sessionCalendarEventPayload;
  "lib/sessions/sessionCalendarTime": typeof lib_sessions_sessionCalendarTime;
  "lib/sessions/sessionCheckout": typeof lib_sessions_sessionCheckout;
  "lib/sessions/sessionLookup": typeof lib_sessions_sessionLookup;
  "lib/sessions/sessionReminderDb": typeof lib_sessions_sessionReminderDb;
  "lib/sessions/sessionRescheduleLinks": typeof lib_sessions_sessionRescheduleLinks;
  "lib/sessions/sessionReservationDb": typeof lib_sessions_sessionReservationDb;
  "lib/sessions/sessionReservations": typeof lib_sessions_sessionReservations;
  "lib/sessions/sessionSavePatch": typeof lib_sessions_sessionSavePatch;
  "lib/sessions/sessionSchedulingArgs": typeof lib_sessions_sessionSchedulingArgs;
  "lib/sessions/sessionSchedulingSave": typeof lib_sessions_sessionSchedulingSave;
  "lib/sessions/sessionSlotReservationAction": typeof lib_sessions_sessionSlotReservationAction;
  "lib/stripe/customInvoices": typeof lib_stripe_customInvoices;
  "lib/stripe/editInvoiceBilling": typeof lib_stripe_editInvoiceBilling;
  "lib/stripe/editInvoiceDb": typeof lib_stripe_editInvoiceDb;
  "lib/stripe/editInvoiceLineItems": typeof lib_stripe_editInvoiceLineItems;
  "lib/stripe/editInvoiceRequest": typeof lib_stripe_editInvoiceRequest;
  "lib/stripe/editInvoiceStripe": typeof lib_stripe_editInvoiceStripe;
  "lib/stripe/invoiceDownloads": typeof lib_stripe_invoiceDownloads;
  "lib/stripe/stripeAdjustmentInvoice": typeof lib_stripe_stripeAdjustmentInvoice;
  "lib/stripe/stripeApiErrors": typeof lib_stripe_stripeApiErrors;
  "lib/stripe/stripeCheckoutSession": typeof lib_stripe_stripeCheckoutSession;
  "lib/stripe/stripeClient": typeof lib_stripe_stripeClient;
  "lib/stripe/stripeInvoice": typeof lib_stripe_stripeInvoice;
  "lib/stripe/stripeInvoiceBillingUrls": typeof lib_stripe_stripeInvoiceBillingUrls;
  "lib/stripe/stripeInvoices": typeof lib_stripe_stripeInvoices;
  "lib/tests/testIds": typeof lib_tests_testIds;
  packageAdjustmentInvoices: typeof packageAdjustmentInvoices;
  packageAdjustments: typeof packageAdjustments;
  packageCheckout: typeof packageCheckout;
  packageCheckoutCompletionHandlers: typeof packageCheckoutCompletionHandlers;
  packagePayment: typeof packagePayment;
  packageReminders: typeof packageReminders;
  packageScheduling: typeof packageScheduling;
  packageSchedulingCalendar: typeof packageSchedulingCalendar;
  packages: typeof packages;
  receiptEmails: typeof receiptEmails;
  "services/auth": typeof services_auth;
  "services/authPermissions": typeof services_authPermissions;
  "services/booking/bookingClaimedSession": typeof services_booking_bookingClaimedSession;
  "services/booking/bookingConfirmation": typeof services_booking_bookingConfirmation;
  "services/booking/bookingConfirmationMutations": typeof services_booking_bookingConfirmationMutations;
  "services/booking/bookingConfirmationWorkflow": typeof services_booking_bookingConfirmationWorkflow;
  "services/booking/bookingFormValidators": typeof services_booking_bookingFormValidators;
  "services/booking/bookingReceiptEmails": typeof services_booking_bookingReceiptEmails;
  "services/booking/bookingReceiptResend": typeof services_booking_bookingReceiptResend;
  "services/booking/bookingSettings": typeof services_booking_bookingSettings;
  "services/booking/bookingSubmission": typeof services_booking_bookingSubmission;
  "services/booking/sessionCheckout": typeof services_booking_sessionCheckout;
  "services/booking/sessionReminderEmail": typeof services_booking_sessionReminderEmail;
  "services/drive/cleanupCancelledSessionDrive": typeof services_drive_cleanupCancelledSessionDrive;
  "services/drive/clientDrivePermissions": typeof services_drive_clientDrivePermissions;
  "services/drive/drive": typeof services_drive_drive;
  "services/drive/driveClientPermissions": typeof services_drive_driveClientPermissions;
  "services/drive/driveEditorPermissions": typeof services_drive_driveEditorPermissions;
  "services/drive/driveInternal": typeof services_drive_driveInternal;
  "services/drive/driveInternalClientAccess": typeof services_drive_driveInternalClientAccess;
  "services/drive/driveInternalEditor": typeof services_drive_driveInternalEditor;
  "services/drive/driveSetupQuery": typeof services_drive_driveSetupQuery;
  "services/drive/driveStatusQuery": typeof services_drive_driveStatusQuery;
  "services/drive/editorDrivePermissions": typeof services_drive_editorDrivePermissions;
  "services/drive/editorRetirement": typeof services_drive_editorRetirement;
  "services/drive/ensureSessionDriveFolderClientSteps": typeof services_drive_ensureSessionDriveFolderClientSteps;
  "services/drive/ensureSessionDriveFolderHelpers": typeof services_drive_ensureSessionDriveFolderHelpers;
  "services/drive/ensureSessionDriveFolderSessionSteps": typeof services_drive_ensureSessionDriveFolderSessionSteps;
  "services/drive/ensureSessionDriveFolderSteps": typeof services_drive_ensureSessionDriveFolderSteps;
  "services/drive/ensureSessionDriveFolders": typeof services_drive_ensureSessionDriveFolders;
  "services/drive/googleDriveFolderTree": typeof services_drive_googleDriveFolderTree;
  "services/editor/deliverablesEmail": typeof services_editor_deliverablesEmail;
  "services/editor/deliverablesReviewReadyEmail": typeof services_editor_deliverablesReviewReadyEmail;
  "services/editor/loadSessionForDeliverables": typeof services_editor_loadSessionForDeliverables;
  "services/editor/sessionEditStatus": typeof services_editor_sessionEditStatus;
  "services/email/bookingCustomerEmails": typeof services_email_bookingCustomerEmails;
  "services/email/hostBookingEmails": typeof services_email_hostBookingEmails;
  "services/email/packageReminderEmails": typeof services_email_packageReminderEmails;
  "services/email/templateEmails": typeof services_email_templateEmails;
  "services/employees/employeeInvitation": typeof services_employees_employeeInvitation;
  "services/employees/employeeManagement": typeof services_employees_employeeManagement;
  "services/feedback/feedbackEmail": typeof services_feedback_feedbackEmail;
  "services/feedback/submitFeedback": typeof services_feedback_submitFeedback;
  "services/googleCalendar/cancelBookingFromAdmin": typeof services_googleCalendar_cancelBookingFromAdmin;
  "services/googleCalendar/packageCalendarAvailability": typeof services_googleCalendar_packageCalendarAvailability;
  "services/googleCalendar/packageCalendarDetails": typeof services_googleCalendar_packageCalendarDetails;
  "services/googleCalendar/packageSchedulingCalendar": typeof services_googleCalendar_packageSchedulingCalendar;
  "services/googleCalendar/sessionAdminUpdate": typeof services_googleCalendar_sessionAdminUpdate;
  "services/googleCalendar/sessionCalendar": typeof services_googleCalendar_sessionCalendar;
  "services/googleCalendar/sessionCalendarAvailability": typeof services_googleCalendar_sessionCalendarAvailability;
  "services/googleCalendar/sessionCalendarAvailabilityLoad": typeof services_googleCalendar_sessionCalendarAvailabilityLoad;
  "services/googleCalendar/sessionCalendarEvent": typeof services_googleCalendar_sessionCalendarEvent;
  "services/googleCalendar/sessionCalendarEventOrchestrationSteps": typeof services_googleCalendar_sessionCalendarEventOrchestrationSteps;
  "services/googleCalendar/sessionCalendarReschedule": typeof services_googleCalendar_sessionCalendarReschedule;
  "services/googleCalendar/sessionCalendarTime": typeof services_googleCalendar_sessionCalendarTime;
  "services/googleCalendar/sessionCalendarTimingSync": typeof services_googleCalendar_sessionCalendarTimingSync;
  "services/packages/claimedPackageCheckoutCompletion": typeof services_packages_claimedPackageCheckoutCompletion;
  "services/packages/packageAdjustmentCron": typeof services_packages_packageAdjustmentCron;
  "services/packages/packageAdjustmentInvoiceEmail": typeof services_packages_packageAdjustmentInvoiceEmail;
  "services/packages/packageAdjustmentInvoicePayment": typeof services_packages_packageAdjustmentInvoicePayment;
  "services/packages/packageAdjustmentInvoiceSend": typeof services_packages_packageAdjustmentInvoiceSend;
  "services/packages/packageAdjustments": typeof services_packages_packageAdjustments;
  "services/packages/packageAdminMutations": typeof services_packages_packageAdminMutations;
  "services/packages/packageAdminQueries": typeof services_packages_packageAdminQueries;
  "services/packages/packageArchive": typeof services_packages_packageArchive;
  "services/packages/packageBookingsReceiptSync": typeof services_packages_packageBookingsReceiptSync;
  "services/packages/packageCheckoutCompletion": typeof services_packages_packageCheckoutCompletion;
  "services/packages/packageCheckoutMutations": typeof services_packages_packageCheckoutMutations;
  "services/packages/packageCheckoutSession": typeof services_packages_packageCheckoutSession;
  "services/packages/packageInternalMutations": typeof services_packages_packageInternalMutations;
  "services/packages/packageLookup": typeof services_packages_packageLookup;
  "services/packages/packagePaidEmailResend": typeof services_packages_packagePaidEmailResend;
  "services/packages/packagePaidEmailSend": typeof services_packages_packagePaidEmailSend;
  "services/packages/packageReminderMutations": typeof services_packages_packageReminderMutations;
  "services/packages/packageReminders": typeof services_packages_packageReminders;
  "services/packages/packageSessionCancel": typeof services_packages_packageSessionCancel;
  "services/packages/packageSessionMutations": typeof services_packages_packageSessionMutations;
  "services/packages/packageSessionScheduling": typeof services_packages_packageSessionScheduling;
  "services/packages/packageSessionSchedulingTypes": typeof services_packages_packageSessionSchedulingTypes;
  "services/packages/packageTokenScheduling": typeof services_packages_packageTokenScheduling;
  "services/requirePermissionActions": typeof services_requirePermissionActions;
  "services/sessions/sessionArchive": typeof services_sessions_sessionArchive;
  "services/sessions/sessionDeliverables": typeof services_sessions_sessionDeliverables;
  "services/sessions/sessionEditorAssignment": typeof services_sessions_sessionEditorAssignment;
  "services/sessions/sessionLookup": typeof services_sessions_sessionLookup;
  "services/sessions/sessionMutations": typeof services_sessions_sessionMutations;
  "services/sessions/sessionQueries": typeof services_sessions_sessionQueries;
  "services/sessions/sessionReminderCron": typeof services_sessions_sessionReminderCron;
  "services/sessions/sessionReminderMutations": typeof services_sessions_sessionReminderMutations;
  "services/sessions/sessionReschedule": typeof services_sessions_sessionReschedule;
  "services/sessions/sessionRescheduleEmails": typeof services_sessions_sessionRescheduleEmails;
  "services/sessions/sessionReservationValidators": typeof services_sessions_sessionReservationValidators;
  "services/sessions/sessionReservations": typeof services_sessions_sessionReservations;
  "services/sessions/sessionSchedulingSave": typeof services_sessions_sessionSchedulingSave;
  "services/sessions/sessions": typeof services_sessions_sessions;
  "services/sessions/sessionsEditor": typeof services_sessions_sessionsEditor;
  "services/stripe/bookingCustomInvoice": typeof services_stripe_bookingCustomInvoice;
  "services/stripe/editInvoiceBilling": typeof services_stripe_editInvoiceBilling;
  "services/stripe/editInvoiceSend": typeof services_stripe_editInvoiceSend;
  "services/stripe/editInvoiceValidators": typeof services_stripe_editInvoiceValidators;
  "services/stripe/invoicePdf": typeof services_stripe_invoicePdf;
  "services/stripe/stripeCheckoutSession": typeof services_stripe_stripeCheckoutSession;
  "services/stripe/stripeInvoiceMutations": typeof services_stripe_stripeInvoiceMutations;
  "services/stripe/stripeInvoicePayment": typeof services_stripe_stripeInvoicePayment;
  "services/stripe/stripeInvoiceSend": typeof services_stripe_stripeInvoiceSend;
  "services/stripe/stripeInvoices": typeof services_stripe_stripeInvoices;
  sessionCheckout: typeof sessionCheckout;
  sessionReminders: typeof sessionReminders;
  sessionReschedule: typeof sessionReschedule;
  sessionScheduling: typeof sessionScheduling;
  sessions: typeof sessions;
  sessionsDriveInternal: typeof sessionsDriveInternal;
  stripe: typeof stripe;
  stripeInvoices: typeof stripeInvoices;
  stripeInvoicing: typeof stripeInvoicing;
  "tests/insertDocumentDefaults": typeof tests_insertDocumentDefaults;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  rateLimiter: import("@convex-dev/rate-limiter/_generated/component.js").ComponentApi<"rateLimiter">;
};
