/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as booking_bookingConfirmation from "../booking/bookingConfirmation.js";
import type * as booking_lib_bookingAddonQuantities from "../booking/lib/bookingAddonQuantities.js";
import type * as booking_lib_bookingConfirmationActionBoundaries from "../booking/lib/bookingConfirmationActionBoundaries.js";
import type * as booking_lib_bookingConfirmationClaim from "../booking/lib/bookingConfirmationClaim.js";
import type * as booking_lib_bookingConfirmationSave from "../booking/lib/bookingConfirmationSave.js";
import type * as booking_lib_bookingConfirmationSessionPatches from "../booking/lib/bookingConfirmationSessionPatches.js";
import type * as booking_lib_bookingFormFields from "../booking/lib/bookingFormFields.js";
import type * as booking_lib_bookingInvoicePdfRender from "../booking/lib/bookingInvoicePdfRender.js";
import type * as booking_lib_bookingReceipt from "../booking/lib/bookingReceipt.js";
import type * as booking_lib_bookingReceiptEmailPipeline from "../booking/lib/bookingReceiptEmailPipeline.js";
import type * as booking_lib_bookingSettings from "../booking/lib/bookingSettings.js";
import type * as booking_lib_bookingSubmission from "../booking/lib/bookingSubmission.js";
import type * as booking_services_bookingClaimedSession from "../booking/services/bookingClaimedSession.js";
import type * as booking_services_bookingConfirmation from "../booking/services/bookingConfirmation.js";
import type * as booking_services_bookingConfirmationMutations from "../booking/services/bookingConfirmationMutations.js";
import type * as booking_services_bookingConfirmationWorkflow from "../booking/services/bookingConfirmationWorkflow.js";
import type * as booking_services_bookingFormValidators from "../booking/services/bookingFormValidators.js";
import type * as booking_services_bookingReceiptEmails from "../booking/services/bookingReceiptEmails.js";
import type * as booking_services_bookingReceiptResend from "../booking/services/bookingReceiptResend.js";
import type * as booking_services_bookingSettings from "../booking/services/bookingSettings.js";
import type * as booking_services_bookingSubmission from "../booking/services/bookingSubmission.js";
import type * as booking_services_sessionCheckout from "../booking/services/sessionCheckout.js";
import type * as booking_services_sessionReminderEmail from "../booking/services/sessionReminderEmail.js";
import type * as booking_settings from "../booking/settings.js";
import type * as crons from "../crons.js";
import type * as devSeed from "../devSeed.js";
import type * as drive_drive from "../drive/drive.js";
import type * as drive_lib_driveBookingDriveClient from "../drive/lib/driveBookingDriveClient.js";
import type * as drive_lib_driveClientAccess from "../drive/lib/driveClientAccess.js";
import type * as drive_lib_driveEditor from "../drive/lib/driveEditor.js";
import type * as drive_lib_driveFolderTreeValidation from "../drive/lib/driveFolderTreeValidation.js";
import type * as drive_lib_driveFolders from "../drive/lib/driveFolders.js";
import type * as drive_lib_driveLookup from "../drive/lib/driveLookup.js";
import type * as drive_lib_driveScheduling from "../drive/lib/driveScheduling.js";
import type * as drive_lib_driveSetupLoad from "../drive/lib/driveSetupLoad.js";
import type * as drive_lib_driveStatus from "../drive/lib/driveStatus.js";
import type * as drive_lib_editorRetirement from "../drive/lib/editorRetirement.js";
import type * as drive_lib_googleDrive from "../drive/lib/googleDrive.js";
import type * as drive_lib_sessionFolders_allocateNumbers from "../drive/lib/sessionFolders/allocateNumbers.js";
import type * as drive_lib_sessionFolders_cancelCleanup from "../drive/lib/sessionFolders/cancelCleanup.js";
import type * as drive_lib_sessionFolders_clearSessionRecords from "../drive/lib/sessionFolders/clearSessionRecords.js";
import type * as drive_lib_sessionFolders_driveSetupInfo from "../drive/lib/sessionFolders/driveSetupInfo.js";
import type * as drive_lib_sessionFolders_resolveFolderNames from "../drive/lib/sessionFolders/resolveFolderNames.js";
import type * as drive_services_cleanupCancelledSessionDrive from "../drive/services/cleanupCancelledSessionDrive.js";
import type * as drive_services_clientDrivePermissions from "../drive/services/clientDrivePermissions.js";
import type * as drive_services_drive from "../drive/services/drive.js";
import type * as drive_services_driveClientPermissions from "../drive/services/driveClientPermissions.js";
import type * as drive_services_driveEditorPermissions from "../drive/services/driveEditorPermissions.js";
import type * as drive_services_driveInternal from "../drive/services/driveInternal.js";
import type * as drive_services_driveInternalClientAccess from "../drive/services/driveInternalClientAccess.js";
import type * as drive_services_driveInternalEditor from "../drive/services/driveInternalEditor.js";
import type * as drive_services_driveSetupQuery from "../drive/services/driveSetupQuery.js";
import type * as drive_services_driveStatusQuery from "../drive/services/driveStatusQuery.js";
import type * as drive_services_editorDrivePermissions from "../drive/services/editorDrivePermissions.js";
import type * as drive_services_editorRetirement from "../drive/services/editorRetirement.js";
import type * as drive_services_ensureSessionDriveFolderClientSteps from "../drive/services/ensureSessionDriveFolderClientSteps.js";
import type * as drive_services_ensureSessionDriveFolderHelpers from "../drive/services/ensureSessionDriveFolderHelpers.js";
import type * as drive_services_ensureSessionDriveFolderSessionSteps from "../drive/services/ensureSessionDriveFolderSessionSteps.js";
import type * as drive_services_ensureSessionDriveFolderSteps from "../drive/services/ensureSessionDriveFolderSteps.js";
import type * as drive_services_ensureSessionDriveFolders from "../drive/services/ensureSessionDriveFolders.js";
import type * as drive_services_googleDriveFolderTree from "../drive/services/googleDriveFolderTree.js";
import type * as editor_deliverablesEmail from "../editor/deliverablesEmail.js";
import type * as editor_deliverablesReviewEmail from "../editor/deliverablesReviewEmail.js";
import type * as editor_lib_deliverablesReviewNotification from "../editor/lib/deliverablesReviewNotification.js";
import type * as editor_lib_editorAccess from "../editor/lib/editorAccess.js";
import type * as editor_lib_editorAssignments from "../editor/lib/editorAssignments.js";
import type * as editor_lib_editorSessions from "../editor/lib/editorSessions.js";
import type * as editor_services_deliverablesEmail from "../editor/services/deliverablesEmail.js";
import type * as editor_services_deliverablesReviewReadyEmail from "../editor/services/deliverablesReviewReadyEmail.js";
import type * as editor_services_loadSessionForDeliverables from "../editor/services/loadSessionForDeliverables.js";
import type * as editor_services_sessionEditStatus from "../editor/services/sessionEditStatus.js";
import type * as email_receiptEmails from "../email/receiptEmails.js";
import type * as email_services_bookingCustomerEmails from "../email/services/bookingCustomerEmails.js";
import type * as email_services_hostBookingEmails from "../email/services/hostBookingEmails.js";
import type * as email_services_packageReminderEmails from "../email/services/packageReminderEmails.js";
import type * as email_services_templateEmails from "../email/services/templateEmails.js";
import type * as employees_employeeInvitations from "../employees/employeeInvitations.js";
import type * as employees_employees from "../employees/employees.js";
import type * as employees_services_employeeInvitation from "../employees/services/employeeInvitation.js";
import type * as employees_services_employeeManagement from "../employees/services/employeeManagement.js";
import type * as env from "../env.js";
import type * as feedback_lib_feedback from "../feedback/lib/feedback.js";
import type * as feedback_public from "../feedback/public.js";
import type * as feedback_services_feedbackEmail from "../feedback/services/feedbackEmail.js";
import type * as feedback_services_submitFeedback from "../feedback/services/submitFeedback.js";
import type * as googleCalendar_googleCalendar from "../googleCalendar/googleCalendar.js";
import type * as googleCalendar_lib_googleAuth from "../googleCalendar/lib/googleAuth.js";
import type * as googleCalendar_lib_googleCalendarAvailability from "../googleCalendar/lib/googleCalendarAvailability.js";
import type * as googleCalendar_lib_googleCalendarClient from "../googleCalendar/lib/googleCalendarClient.js";
import type * as googleCalendar_lib_googleCalendarErrors from "../googleCalendar/lib/googleCalendarErrors.js";
import type * as googleCalendar_lib_googleCalendarEventCalls from "../googleCalendar/lib/googleCalendarEventCalls.js";
import type * as googleCalendar_lib_packageCalendarDetails from "../googleCalendar/lib/packageCalendarDetails.js";
import type * as googleCalendar_services_cancelBookingFromAdmin from "../googleCalendar/services/cancelBookingFromAdmin.js";
import type * as googleCalendar_services_packageCalendarAvailability from "../googleCalendar/services/packageCalendarAvailability.js";
import type * as googleCalendar_services_packageCalendarDetails from "../googleCalendar/services/packageCalendarDetails.js";
import type * as googleCalendar_services_packageSchedulingCalendar from "../googleCalendar/services/packageSchedulingCalendar.js";
import type * as googleCalendar_services_sessionAdminUpdate from "../googleCalendar/services/sessionAdminUpdate.js";
import type * as googleCalendar_services_sessionCalendar from "../googleCalendar/services/sessionCalendar.js";
import type * as googleCalendar_services_sessionCalendarAvailability from "../googleCalendar/services/sessionCalendarAvailability.js";
import type * as googleCalendar_services_sessionCalendarAvailabilityLoad from "../googleCalendar/services/sessionCalendarAvailabilityLoad.js";
import type * as googleCalendar_services_sessionCalendarEvent from "../googleCalendar/services/sessionCalendarEvent.js";
import type * as googleCalendar_services_sessionCalendarEventOrchestrationSteps from "../googleCalendar/services/sessionCalendarEventOrchestrationSteps.js";
import type * as googleCalendar_services_sessionCalendarReschedule from "../googleCalendar/services/sessionCalendarReschedule.js";
import type * as googleCalendar_services_sessionCalendarTime from "../googleCalendar/services/sessionCalendarTime.js";
import type * as googleCalendar_services_sessionCalendarTimingSync from "../googleCalendar/services/sessionCalendarTimingSync.js";
import type * as http from "../http.js";
import type * as packages_lib_packageAdjustmentInvoicePayment from "../packages/lib/packageAdjustmentInvoicePayment.js";
import type * as packages_lib_packageAdjustmentJobs from "../packages/lib/packageAdjustmentJobs.js";
import type * as packages_lib_packageAdjustmentScheduling from "../packages/lib/packageAdjustmentScheduling.js";
import type * as packages_lib_packageAdjustments from "../packages/lib/packageAdjustments.js";
import type * as packages_lib_packageArchive from "../packages/lib/packageArchive.js";
import type * as packages_lib_packageBookingsReceiptSync from "../packages/lib/packageBookingsReceiptSync.js";
import type * as packages_lib_packageCheckout from "../packages/lib/packageCheckout.js";
import type * as packages_lib_packageCheckoutClaim from "../packages/lib/packageCheckoutClaim.js";
import type * as packages_lib_packageLookup from "../packages/lib/packageLookup.js";
import type * as packages_lib_packagePaidLifecycle from "../packages/lib/packagePaidLifecycle.js";
import type * as packages_lib_packagePayment from "../packages/lib/packagePayment.js";
import type * as packages_lib_packageReminderDb from "../packages/lib/packageReminderDb.js";
import type * as packages_lib_packageReminders from "../packages/lib/packageReminders.js";
import type * as packages_lib_packageScheduling from "../packages/lib/packageScheduling.js";
import type * as packages_lib_packageSchedulingActionBoundaries from "../packages/lib/packageSchedulingActionBoundaries.js";
import type * as packages_lib_packageSessionBookings from "../packages/lib/packageSessionBookings.js";
import type * as packages_lib_packageSessionCapacity from "../packages/lib/packageSessionCapacity.js";
import type * as packages_lib_packageTokenView from "../packages/lib/packageTokenView.js";
import type * as packages_lib_packageUpdates from "../packages/lib/packageUpdates.js";
import type * as packages_packageAdjustmentInvoices from "../packages/packageAdjustmentInvoices.js";
import type * as packages_packageAdjustments from "../packages/packageAdjustments.js";
import type * as packages_packageCheckout from "../packages/packageCheckout.js";
import type * as packages_packageCheckoutCompletionHandlers from "../packages/packageCheckoutCompletionHandlers.js";
import type * as packages_packagePayment from "../packages/packagePayment.js";
import type * as packages_packageReminders from "../packages/packageReminders.js";
import type * as packages_packageScheduling from "../packages/packageScheduling.js";
import type * as packages_packageSchedulingCalendar from "../packages/packageSchedulingCalendar.js";
import type * as packages_packages from "../packages/packages.js";
import type * as packages_services_claimedPackageCheckoutCompletion from "../packages/services/claimedPackageCheckoutCompletion.js";
import type * as packages_services_packageAdjustmentCron from "../packages/services/packageAdjustmentCron.js";
import type * as packages_services_packageAdjustmentInvoiceEmail from "../packages/services/packageAdjustmentInvoiceEmail.js";
import type * as packages_services_packageAdjustmentInvoicePayment from "../packages/services/packageAdjustmentInvoicePayment.js";
import type * as packages_services_packageAdjustmentInvoiceSend from "../packages/services/packageAdjustmentInvoiceSend.js";
import type * as packages_services_packageAdjustments from "../packages/services/packageAdjustments.js";
import type * as packages_services_packageAdminMutations from "../packages/services/packageAdminMutations.js";
import type * as packages_services_packageAdminQueries from "../packages/services/packageAdminQueries.js";
import type * as packages_services_packageArchive from "../packages/services/packageArchive.js";
import type * as packages_services_packageBookingsReceiptSync from "../packages/services/packageBookingsReceiptSync.js";
import type * as packages_services_packageCheckoutCompletion from "../packages/services/packageCheckoutCompletion.js";
import type * as packages_services_packageCheckoutMutations from "../packages/services/packageCheckoutMutations.js";
import type * as packages_services_packageCheckoutSession from "../packages/services/packageCheckoutSession.js";
import type * as packages_services_packageInternalMutations from "../packages/services/packageInternalMutations.js";
import type * as packages_services_packageLookup from "../packages/services/packageLookup.js";
import type * as packages_services_packagePaidEmailResend from "../packages/services/packagePaidEmailResend.js";
import type * as packages_services_packagePaidEmailSend from "../packages/services/packagePaidEmailSend.js";
import type * as packages_services_packageReminderMutations from "../packages/services/packageReminderMutations.js";
import type * as packages_services_packageReminders from "../packages/services/packageReminders.js";
import type * as packages_services_packageSessionCancel from "../packages/services/packageSessionCancel.js";
import type * as packages_services_packageSessionMutations from "../packages/services/packageSessionMutations.js";
import type * as packages_services_packageSessionScheduling from "../packages/services/packageSessionScheduling.js";
import type * as packages_services_packageSessionSchedulingTypes from "../packages/services/packageSessionSchedulingTypes.js";
import type * as packages_services_packageTokenScheduling from "../packages/services/packageTokenScheduling.js";
import type * as sessions_lib_pendingCheckoutSession from "../sessions/lib/pendingCheckoutSession.js";
import type * as sessions_lib_sessionAdminEdit from "../sessions/lib/sessionAdminEdit.js";
import type * as sessions_lib_sessionArchive from "../sessions/lib/sessionArchive.js";
import type * as sessions_lib_sessionCalendarActionBoundaries from "../sessions/lib/sessionCalendarActionBoundaries.js";
import type * as sessions_lib_sessionCalendarEventPayload from "../sessions/lib/sessionCalendarEventPayload.js";
import type * as sessions_lib_sessionCalendarTime from "../sessions/lib/sessionCalendarTime.js";
import type * as sessions_lib_sessionCheckout from "../sessions/lib/sessionCheckout.js";
import type * as sessions_lib_sessionLookup from "../sessions/lib/sessionLookup.js";
import type * as sessions_lib_sessionReminderDb from "../sessions/lib/sessionReminderDb.js";
import type * as sessions_lib_sessionRescheduleLinks from "../sessions/lib/sessionRescheduleLinks.js";
import type * as sessions_lib_sessionReservationDb from "../sessions/lib/sessionReservationDb.js";
import type * as sessions_lib_sessionReservations from "../sessions/lib/sessionReservations.js";
import type * as sessions_lib_sessionSavePatch from "../sessions/lib/sessionSavePatch.js";
import type * as sessions_lib_sessionSchedulingArgs from "../sessions/lib/sessionSchedulingArgs.js";
import type * as sessions_lib_sessionSchedulingSave from "../sessions/lib/sessionSchedulingSave.js";
import type * as sessions_lib_sessionSlotReservationAction from "../sessions/lib/sessionSlotReservationAction.js";
import type * as sessions_services_sessionArchive from "../sessions/services/sessionArchive.js";
import type * as sessions_services_sessionDeliverables from "../sessions/services/sessionDeliverables.js";
import type * as sessions_services_sessionEditorAssignment from "../sessions/services/sessionEditorAssignment.js";
import type * as sessions_services_sessionLookup from "../sessions/services/sessionLookup.js";
import type * as sessions_services_sessionMutations from "../sessions/services/sessionMutations.js";
import type * as sessions_services_sessionQueries from "../sessions/services/sessionQueries.js";
import type * as sessions_services_sessionReminderCron from "../sessions/services/sessionReminderCron.js";
import type * as sessions_services_sessionReminderMutations from "../sessions/services/sessionReminderMutations.js";
import type * as sessions_services_sessionReschedule from "../sessions/services/sessionReschedule.js";
import type * as sessions_services_sessionRescheduleEmails from "../sessions/services/sessionRescheduleEmails.js";
import type * as sessions_services_sessionReservationValidators from "../sessions/services/sessionReservationValidators.js";
import type * as sessions_services_sessionReservations from "../sessions/services/sessionReservations.js";
import type * as sessions_services_sessionSchedulingSave from "../sessions/services/sessionSchedulingSave.js";
import type * as sessions_services_sessions from "../sessions/services/sessions.js";
import type * as sessions_services_sessionsEditor from "../sessions/services/sessionsEditor.js";
import type * as sessions_sessionCheckout from "../sessions/sessionCheckout.js";
import type * as sessions_sessionReminders from "../sessions/sessionReminders.js";
import type * as sessions_sessionReschedule from "../sessions/sessionReschedule.js";
import type * as sessions_sessionScheduling from "../sessions/sessionScheduling.js";
import type * as sessions_sessions from "../sessions/sessions.js";
import type * as sessions_sessionsDriveInternal from "../sessions/sessionsDriveInternal.js";
import type * as shared_auth from "../shared/auth.js";
import type * as shared_lib_adminSearch_adminListSearchPage from "../shared/lib/adminSearch/adminListSearchPage.js";
import type * as shared_lib_adminSearch_adminSearchBlob from "../shared/lib/adminSearch/adminSearchBlob.js";
import type * as shared_lib_adminSearch_adminSearchDateParse from "../shared/lib/adminSearch/adminSearchDateParse.js";
import type * as shared_lib_adminSearch_adminSearchPrefixFilters from "../shared/lib/adminSearch/adminSearchPrefixFilters.js";
import type * as shared_lib_adminSearch_adminSearchQuery from "../shared/lib/adminSearch/adminSearchQuery.js";
import type * as shared_lib_archiveState from "../shared/lib/archiveState.js";
import type * as shared_lib_auth from "../shared/lib/auth.js";
import type * as shared_lib_clerkInvitations from "../shared/lib/clerkInvitations.js";
import type * as shared_lib_contactNormalization from "../shared/lib/contactNormalization.js";
import type * as shared_lib_crypto_bytesToHex from "../shared/lib/crypto/bytesToHex.js";
import type * as shared_lib_email_emailDomain from "../shared/lib/email/emailDomain.js";
import type * as shared_lib_email_emailRenders from "../shared/lib/email/emailRenders.js";
import type * as shared_lib_email_emailSend from "../shared/lib/email/emailSend.js";
import type * as shared_lib_listAdminPackages from "../shared/lib/listAdminPackages.js";
import type * as shared_lib_listAdminSessions from "../shared/lib/listAdminSessions.js";
import type * as shared_lib_rateLimits from "../shared/lib/rateLimits.js";
import type * as shared_lib_reminderScheduleTime from "../shared/lib/reminderScheduleTime.js";
import type * as shared_lib_result from "../shared/lib/result.js";
import type * as shared_lib_tests_testIds from "../shared/lib/tests/testIds.js";
import type * as shared_services_auth from "../shared/services/auth.js";
import type * as shared_services_authPermissions from "../shared/services/authPermissions.js";
import type * as shared_services_requirePermissionActions from "../shared/services/requirePermissionActions.js";
import type * as stripe_customInvoices from "../stripe/customInvoices.js";
import type * as stripe_editInvoices from "../stripe/editInvoices.js";
import type * as stripe_editInvoicing from "../stripe/editInvoicing.js";
import type * as stripe_invoices from "../stripe/invoices.js";
import type * as stripe_lib_customInvoices from "../stripe/lib/customInvoices.js";
import type * as stripe_lib_editInvoiceBilling from "../stripe/lib/editInvoiceBilling.js";
import type * as stripe_lib_editInvoiceDb from "../stripe/lib/editInvoiceDb.js";
import type * as stripe_lib_editInvoiceLineItems from "../stripe/lib/editInvoiceLineItems.js";
import type * as stripe_lib_editInvoiceRequest from "../stripe/lib/editInvoiceRequest.js";
import type * as stripe_lib_editInvoiceStripe from "../stripe/lib/editInvoiceStripe.js";
import type * as stripe_lib_invoiceDownloads from "../stripe/lib/invoiceDownloads.js";
import type * as stripe_lib_stripeAdjustmentInvoice from "../stripe/lib/stripeAdjustmentInvoice.js";
import type * as stripe_lib_stripeApiErrors from "../stripe/lib/stripeApiErrors.js";
import type * as stripe_lib_stripeCheckoutSession from "../stripe/lib/stripeCheckoutSession.js";
import type * as stripe_lib_stripeClient from "../stripe/lib/stripeClient.js";
import type * as stripe_lib_stripeInvoice from "../stripe/lib/stripeInvoice.js";
import type * as stripe_lib_stripeInvoiceBillingUrls from "../stripe/lib/stripeInvoiceBillingUrls.js";
import type * as stripe_lib_stripeInvoices from "../stripe/lib/stripeInvoices.js";
import type * as stripe_services_bookingCustomInvoice from "../stripe/services/bookingCustomInvoice.js";
import type * as stripe_services_editInvoiceBilling from "../stripe/services/editInvoiceBilling.js";
import type * as stripe_services_editInvoiceSend from "../stripe/services/editInvoiceSend.js";
import type * as stripe_services_editInvoiceValidators from "../stripe/services/editInvoiceValidators.js";
import type * as stripe_services_invoicePdf from "../stripe/services/invoicePdf.js";
import type * as stripe_services_stripeCheckoutSession from "../stripe/services/stripeCheckoutSession.js";
import type * as stripe_services_stripeInvoiceMutations from "../stripe/services/stripeInvoiceMutations.js";
import type * as stripe_services_stripeInvoicePayment from "../stripe/services/stripeInvoicePayment.js";
import type * as stripe_services_stripeInvoiceSend from "../stripe/services/stripeInvoiceSend.js";
import type * as stripe_services_stripeInvoices from "../stripe/services/stripeInvoices.js";
import type * as stripe_stripe from "../stripe/stripe.js";
import type * as stripe_stripeInvoices from "../stripe/stripeInvoices.js";
import type * as stripe_stripeInvoicing from "../stripe/stripeInvoicing.js";
import type * as tests_insertDocumentDefaults from "../tests/insertDocumentDefaults.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "booking/bookingConfirmation": typeof booking_bookingConfirmation;
  "booking/lib/bookingAddonQuantities": typeof booking_lib_bookingAddonQuantities;
  "booking/lib/bookingConfirmationActionBoundaries": typeof booking_lib_bookingConfirmationActionBoundaries;
  "booking/lib/bookingConfirmationClaim": typeof booking_lib_bookingConfirmationClaim;
  "booking/lib/bookingConfirmationSave": typeof booking_lib_bookingConfirmationSave;
  "booking/lib/bookingConfirmationSessionPatches": typeof booking_lib_bookingConfirmationSessionPatches;
  "booking/lib/bookingFormFields": typeof booking_lib_bookingFormFields;
  "booking/lib/bookingInvoicePdfRender": typeof booking_lib_bookingInvoicePdfRender;
  "booking/lib/bookingReceipt": typeof booking_lib_bookingReceipt;
  "booking/lib/bookingReceiptEmailPipeline": typeof booking_lib_bookingReceiptEmailPipeline;
  "booking/lib/bookingSettings": typeof booking_lib_bookingSettings;
  "booking/lib/bookingSubmission": typeof booking_lib_bookingSubmission;
  "booking/services/bookingClaimedSession": typeof booking_services_bookingClaimedSession;
  "booking/services/bookingConfirmation": typeof booking_services_bookingConfirmation;
  "booking/services/bookingConfirmationMutations": typeof booking_services_bookingConfirmationMutations;
  "booking/services/bookingConfirmationWorkflow": typeof booking_services_bookingConfirmationWorkflow;
  "booking/services/bookingFormValidators": typeof booking_services_bookingFormValidators;
  "booking/services/bookingReceiptEmails": typeof booking_services_bookingReceiptEmails;
  "booking/services/bookingReceiptResend": typeof booking_services_bookingReceiptResend;
  "booking/services/bookingSettings": typeof booking_services_bookingSettings;
  "booking/services/bookingSubmission": typeof booking_services_bookingSubmission;
  "booking/services/sessionCheckout": typeof booking_services_sessionCheckout;
  "booking/services/sessionReminderEmail": typeof booking_services_sessionReminderEmail;
  "booking/settings": typeof booking_settings;
  crons: typeof crons;
  devSeed: typeof devSeed;
  "drive/drive": typeof drive_drive;
  "drive/lib/driveBookingDriveClient": typeof drive_lib_driveBookingDriveClient;
  "drive/lib/driveClientAccess": typeof drive_lib_driveClientAccess;
  "drive/lib/driveEditor": typeof drive_lib_driveEditor;
  "drive/lib/driveFolderTreeValidation": typeof drive_lib_driveFolderTreeValidation;
  "drive/lib/driveFolders": typeof drive_lib_driveFolders;
  "drive/lib/driveLookup": typeof drive_lib_driveLookup;
  "drive/lib/driveScheduling": typeof drive_lib_driveScheduling;
  "drive/lib/driveSetupLoad": typeof drive_lib_driveSetupLoad;
  "drive/lib/driveStatus": typeof drive_lib_driveStatus;
  "drive/lib/editorRetirement": typeof drive_lib_editorRetirement;
  "drive/lib/googleDrive": typeof drive_lib_googleDrive;
  "drive/lib/sessionFolders/allocateNumbers": typeof drive_lib_sessionFolders_allocateNumbers;
  "drive/lib/sessionFolders/cancelCleanup": typeof drive_lib_sessionFolders_cancelCleanup;
  "drive/lib/sessionFolders/clearSessionRecords": typeof drive_lib_sessionFolders_clearSessionRecords;
  "drive/lib/sessionFolders/driveSetupInfo": typeof drive_lib_sessionFolders_driveSetupInfo;
  "drive/lib/sessionFolders/resolveFolderNames": typeof drive_lib_sessionFolders_resolveFolderNames;
  "drive/services/cleanupCancelledSessionDrive": typeof drive_services_cleanupCancelledSessionDrive;
  "drive/services/clientDrivePermissions": typeof drive_services_clientDrivePermissions;
  "drive/services/drive": typeof drive_services_drive;
  "drive/services/driveClientPermissions": typeof drive_services_driveClientPermissions;
  "drive/services/driveEditorPermissions": typeof drive_services_driveEditorPermissions;
  "drive/services/driveInternal": typeof drive_services_driveInternal;
  "drive/services/driveInternalClientAccess": typeof drive_services_driveInternalClientAccess;
  "drive/services/driveInternalEditor": typeof drive_services_driveInternalEditor;
  "drive/services/driveSetupQuery": typeof drive_services_driveSetupQuery;
  "drive/services/driveStatusQuery": typeof drive_services_driveStatusQuery;
  "drive/services/editorDrivePermissions": typeof drive_services_editorDrivePermissions;
  "drive/services/editorRetirement": typeof drive_services_editorRetirement;
  "drive/services/ensureSessionDriveFolderClientSteps": typeof drive_services_ensureSessionDriveFolderClientSteps;
  "drive/services/ensureSessionDriveFolderHelpers": typeof drive_services_ensureSessionDriveFolderHelpers;
  "drive/services/ensureSessionDriveFolderSessionSteps": typeof drive_services_ensureSessionDriveFolderSessionSteps;
  "drive/services/ensureSessionDriveFolderSteps": typeof drive_services_ensureSessionDriveFolderSteps;
  "drive/services/ensureSessionDriveFolders": typeof drive_services_ensureSessionDriveFolders;
  "drive/services/googleDriveFolderTree": typeof drive_services_googleDriveFolderTree;
  "editor/deliverablesEmail": typeof editor_deliverablesEmail;
  "editor/deliverablesReviewEmail": typeof editor_deliverablesReviewEmail;
  "editor/lib/deliverablesReviewNotification": typeof editor_lib_deliverablesReviewNotification;
  "editor/lib/editorAccess": typeof editor_lib_editorAccess;
  "editor/lib/editorAssignments": typeof editor_lib_editorAssignments;
  "editor/lib/editorSessions": typeof editor_lib_editorSessions;
  "editor/services/deliverablesEmail": typeof editor_services_deliverablesEmail;
  "editor/services/deliverablesReviewReadyEmail": typeof editor_services_deliverablesReviewReadyEmail;
  "editor/services/loadSessionForDeliverables": typeof editor_services_loadSessionForDeliverables;
  "editor/services/sessionEditStatus": typeof editor_services_sessionEditStatus;
  "email/receiptEmails": typeof email_receiptEmails;
  "email/services/bookingCustomerEmails": typeof email_services_bookingCustomerEmails;
  "email/services/hostBookingEmails": typeof email_services_hostBookingEmails;
  "email/services/packageReminderEmails": typeof email_services_packageReminderEmails;
  "email/services/templateEmails": typeof email_services_templateEmails;
  "employees/employeeInvitations": typeof employees_employeeInvitations;
  "employees/employees": typeof employees_employees;
  "employees/services/employeeInvitation": typeof employees_services_employeeInvitation;
  "employees/services/employeeManagement": typeof employees_services_employeeManagement;
  env: typeof env;
  "feedback/lib/feedback": typeof feedback_lib_feedback;
  "feedback/public": typeof feedback_public;
  "feedback/services/feedbackEmail": typeof feedback_services_feedbackEmail;
  "feedback/services/submitFeedback": typeof feedback_services_submitFeedback;
  "googleCalendar/googleCalendar": typeof googleCalendar_googleCalendar;
  "googleCalendar/lib/googleAuth": typeof googleCalendar_lib_googleAuth;
  "googleCalendar/lib/googleCalendarAvailability": typeof googleCalendar_lib_googleCalendarAvailability;
  "googleCalendar/lib/googleCalendarClient": typeof googleCalendar_lib_googleCalendarClient;
  "googleCalendar/lib/googleCalendarErrors": typeof googleCalendar_lib_googleCalendarErrors;
  "googleCalendar/lib/googleCalendarEventCalls": typeof googleCalendar_lib_googleCalendarEventCalls;
  "googleCalendar/lib/packageCalendarDetails": typeof googleCalendar_lib_packageCalendarDetails;
  "googleCalendar/services/cancelBookingFromAdmin": typeof googleCalendar_services_cancelBookingFromAdmin;
  "googleCalendar/services/packageCalendarAvailability": typeof googleCalendar_services_packageCalendarAvailability;
  "googleCalendar/services/packageCalendarDetails": typeof googleCalendar_services_packageCalendarDetails;
  "googleCalendar/services/packageSchedulingCalendar": typeof googleCalendar_services_packageSchedulingCalendar;
  "googleCalendar/services/sessionAdminUpdate": typeof googleCalendar_services_sessionAdminUpdate;
  "googleCalendar/services/sessionCalendar": typeof googleCalendar_services_sessionCalendar;
  "googleCalendar/services/sessionCalendarAvailability": typeof googleCalendar_services_sessionCalendarAvailability;
  "googleCalendar/services/sessionCalendarAvailabilityLoad": typeof googleCalendar_services_sessionCalendarAvailabilityLoad;
  "googleCalendar/services/sessionCalendarEvent": typeof googleCalendar_services_sessionCalendarEvent;
  "googleCalendar/services/sessionCalendarEventOrchestrationSteps": typeof googleCalendar_services_sessionCalendarEventOrchestrationSteps;
  "googleCalendar/services/sessionCalendarReschedule": typeof googleCalendar_services_sessionCalendarReschedule;
  "googleCalendar/services/sessionCalendarTime": typeof googleCalendar_services_sessionCalendarTime;
  "googleCalendar/services/sessionCalendarTimingSync": typeof googleCalendar_services_sessionCalendarTimingSync;
  http: typeof http;
  "packages/lib/packageAdjustmentInvoicePayment": typeof packages_lib_packageAdjustmentInvoicePayment;
  "packages/lib/packageAdjustmentJobs": typeof packages_lib_packageAdjustmentJobs;
  "packages/lib/packageAdjustmentScheduling": typeof packages_lib_packageAdjustmentScheduling;
  "packages/lib/packageAdjustments": typeof packages_lib_packageAdjustments;
  "packages/lib/packageArchive": typeof packages_lib_packageArchive;
  "packages/lib/packageBookingsReceiptSync": typeof packages_lib_packageBookingsReceiptSync;
  "packages/lib/packageCheckout": typeof packages_lib_packageCheckout;
  "packages/lib/packageCheckoutClaim": typeof packages_lib_packageCheckoutClaim;
  "packages/lib/packageLookup": typeof packages_lib_packageLookup;
  "packages/lib/packagePaidLifecycle": typeof packages_lib_packagePaidLifecycle;
  "packages/lib/packagePayment": typeof packages_lib_packagePayment;
  "packages/lib/packageReminderDb": typeof packages_lib_packageReminderDb;
  "packages/lib/packageReminders": typeof packages_lib_packageReminders;
  "packages/lib/packageScheduling": typeof packages_lib_packageScheduling;
  "packages/lib/packageSchedulingActionBoundaries": typeof packages_lib_packageSchedulingActionBoundaries;
  "packages/lib/packageSessionBookings": typeof packages_lib_packageSessionBookings;
  "packages/lib/packageSessionCapacity": typeof packages_lib_packageSessionCapacity;
  "packages/lib/packageTokenView": typeof packages_lib_packageTokenView;
  "packages/lib/packageUpdates": typeof packages_lib_packageUpdates;
  "packages/packageAdjustmentInvoices": typeof packages_packageAdjustmentInvoices;
  "packages/packageAdjustments": typeof packages_packageAdjustments;
  "packages/packageCheckout": typeof packages_packageCheckout;
  "packages/packageCheckoutCompletionHandlers": typeof packages_packageCheckoutCompletionHandlers;
  "packages/packagePayment": typeof packages_packagePayment;
  "packages/packageReminders": typeof packages_packageReminders;
  "packages/packageScheduling": typeof packages_packageScheduling;
  "packages/packageSchedulingCalendar": typeof packages_packageSchedulingCalendar;
  "packages/packages": typeof packages_packages;
  "packages/services/claimedPackageCheckoutCompletion": typeof packages_services_claimedPackageCheckoutCompletion;
  "packages/services/packageAdjustmentCron": typeof packages_services_packageAdjustmentCron;
  "packages/services/packageAdjustmentInvoiceEmail": typeof packages_services_packageAdjustmentInvoiceEmail;
  "packages/services/packageAdjustmentInvoicePayment": typeof packages_services_packageAdjustmentInvoicePayment;
  "packages/services/packageAdjustmentInvoiceSend": typeof packages_services_packageAdjustmentInvoiceSend;
  "packages/services/packageAdjustments": typeof packages_services_packageAdjustments;
  "packages/services/packageAdminMutations": typeof packages_services_packageAdminMutations;
  "packages/services/packageAdminQueries": typeof packages_services_packageAdminQueries;
  "packages/services/packageArchive": typeof packages_services_packageArchive;
  "packages/services/packageBookingsReceiptSync": typeof packages_services_packageBookingsReceiptSync;
  "packages/services/packageCheckoutCompletion": typeof packages_services_packageCheckoutCompletion;
  "packages/services/packageCheckoutMutations": typeof packages_services_packageCheckoutMutations;
  "packages/services/packageCheckoutSession": typeof packages_services_packageCheckoutSession;
  "packages/services/packageInternalMutations": typeof packages_services_packageInternalMutations;
  "packages/services/packageLookup": typeof packages_services_packageLookup;
  "packages/services/packagePaidEmailResend": typeof packages_services_packagePaidEmailResend;
  "packages/services/packagePaidEmailSend": typeof packages_services_packagePaidEmailSend;
  "packages/services/packageReminderMutations": typeof packages_services_packageReminderMutations;
  "packages/services/packageReminders": typeof packages_services_packageReminders;
  "packages/services/packageSessionCancel": typeof packages_services_packageSessionCancel;
  "packages/services/packageSessionMutations": typeof packages_services_packageSessionMutations;
  "packages/services/packageSessionScheduling": typeof packages_services_packageSessionScheduling;
  "packages/services/packageSessionSchedulingTypes": typeof packages_services_packageSessionSchedulingTypes;
  "packages/services/packageTokenScheduling": typeof packages_services_packageTokenScheduling;
  "sessions/lib/pendingCheckoutSession": typeof sessions_lib_pendingCheckoutSession;
  "sessions/lib/sessionAdminEdit": typeof sessions_lib_sessionAdminEdit;
  "sessions/lib/sessionArchive": typeof sessions_lib_sessionArchive;
  "sessions/lib/sessionCalendarActionBoundaries": typeof sessions_lib_sessionCalendarActionBoundaries;
  "sessions/lib/sessionCalendarEventPayload": typeof sessions_lib_sessionCalendarEventPayload;
  "sessions/lib/sessionCalendarTime": typeof sessions_lib_sessionCalendarTime;
  "sessions/lib/sessionCheckout": typeof sessions_lib_sessionCheckout;
  "sessions/lib/sessionLookup": typeof sessions_lib_sessionLookup;
  "sessions/lib/sessionReminderDb": typeof sessions_lib_sessionReminderDb;
  "sessions/lib/sessionRescheduleLinks": typeof sessions_lib_sessionRescheduleLinks;
  "sessions/lib/sessionReservationDb": typeof sessions_lib_sessionReservationDb;
  "sessions/lib/sessionReservations": typeof sessions_lib_sessionReservations;
  "sessions/lib/sessionSavePatch": typeof sessions_lib_sessionSavePatch;
  "sessions/lib/sessionSchedulingArgs": typeof sessions_lib_sessionSchedulingArgs;
  "sessions/lib/sessionSchedulingSave": typeof sessions_lib_sessionSchedulingSave;
  "sessions/lib/sessionSlotReservationAction": typeof sessions_lib_sessionSlotReservationAction;
  "sessions/services/sessionArchive": typeof sessions_services_sessionArchive;
  "sessions/services/sessionDeliverables": typeof sessions_services_sessionDeliverables;
  "sessions/services/sessionEditorAssignment": typeof sessions_services_sessionEditorAssignment;
  "sessions/services/sessionLookup": typeof sessions_services_sessionLookup;
  "sessions/services/sessionMutations": typeof sessions_services_sessionMutations;
  "sessions/services/sessionQueries": typeof sessions_services_sessionQueries;
  "sessions/services/sessionReminderCron": typeof sessions_services_sessionReminderCron;
  "sessions/services/sessionReminderMutations": typeof sessions_services_sessionReminderMutations;
  "sessions/services/sessionReschedule": typeof sessions_services_sessionReschedule;
  "sessions/services/sessionRescheduleEmails": typeof sessions_services_sessionRescheduleEmails;
  "sessions/services/sessionReservationValidators": typeof sessions_services_sessionReservationValidators;
  "sessions/services/sessionReservations": typeof sessions_services_sessionReservations;
  "sessions/services/sessionSchedulingSave": typeof sessions_services_sessionSchedulingSave;
  "sessions/services/sessions": typeof sessions_services_sessions;
  "sessions/services/sessionsEditor": typeof sessions_services_sessionsEditor;
  "sessions/sessionCheckout": typeof sessions_sessionCheckout;
  "sessions/sessionReminders": typeof sessions_sessionReminders;
  "sessions/sessionReschedule": typeof sessions_sessionReschedule;
  "sessions/sessionScheduling": typeof sessions_sessionScheduling;
  "sessions/sessions": typeof sessions_sessions;
  "sessions/sessionsDriveInternal": typeof sessions_sessionsDriveInternal;
  "shared/auth": typeof shared_auth;
  "shared/lib/adminSearch/adminListSearchPage": typeof shared_lib_adminSearch_adminListSearchPage;
  "shared/lib/adminSearch/adminSearchBlob": typeof shared_lib_adminSearch_adminSearchBlob;
  "shared/lib/adminSearch/adminSearchDateParse": typeof shared_lib_adminSearch_adminSearchDateParse;
  "shared/lib/adminSearch/adminSearchPrefixFilters": typeof shared_lib_adminSearch_adminSearchPrefixFilters;
  "shared/lib/adminSearch/adminSearchQuery": typeof shared_lib_adminSearch_adminSearchQuery;
  "shared/lib/archiveState": typeof shared_lib_archiveState;
  "shared/lib/auth": typeof shared_lib_auth;
  "shared/lib/clerkInvitations": typeof shared_lib_clerkInvitations;
  "shared/lib/contactNormalization": typeof shared_lib_contactNormalization;
  "shared/lib/crypto/bytesToHex": typeof shared_lib_crypto_bytesToHex;
  "shared/lib/email/emailDomain": typeof shared_lib_email_emailDomain;
  "shared/lib/email/emailRenders": typeof shared_lib_email_emailRenders;
  "shared/lib/email/emailSend": typeof shared_lib_email_emailSend;
  "shared/lib/listAdminPackages": typeof shared_lib_listAdminPackages;
  "shared/lib/listAdminSessions": typeof shared_lib_listAdminSessions;
  "shared/lib/rateLimits": typeof shared_lib_rateLimits;
  "shared/lib/reminderScheduleTime": typeof shared_lib_reminderScheduleTime;
  "shared/lib/result": typeof shared_lib_result;
  "shared/lib/tests/testIds": typeof shared_lib_tests_testIds;
  "shared/services/auth": typeof shared_services_auth;
  "shared/services/authPermissions": typeof shared_services_authPermissions;
  "shared/services/requirePermissionActions": typeof shared_services_requirePermissionActions;
  "stripe/customInvoices": typeof stripe_customInvoices;
  "stripe/editInvoices": typeof stripe_editInvoices;
  "stripe/editInvoicing": typeof stripe_editInvoicing;
  "stripe/invoices": typeof stripe_invoices;
  "stripe/lib/customInvoices": typeof stripe_lib_customInvoices;
  "stripe/lib/editInvoiceBilling": typeof stripe_lib_editInvoiceBilling;
  "stripe/lib/editInvoiceDb": typeof stripe_lib_editInvoiceDb;
  "stripe/lib/editInvoiceLineItems": typeof stripe_lib_editInvoiceLineItems;
  "stripe/lib/editInvoiceRequest": typeof stripe_lib_editInvoiceRequest;
  "stripe/lib/editInvoiceStripe": typeof stripe_lib_editInvoiceStripe;
  "stripe/lib/invoiceDownloads": typeof stripe_lib_invoiceDownloads;
  "stripe/lib/stripeAdjustmentInvoice": typeof stripe_lib_stripeAdjustmentInvoice;
  "stripe/lib/stripeApiErrors": typeof stripe_lib_stripeApiErrors;
  "stripe/lib/stripeCheckoutSession": typeof stripe_lib_stripeCheckoutSession;
  "stripe/lib/stripeClient": typeof stripe_lib_stripeClient;
  "stripe/lib/stripeInvoice": typeof stripe_lib_stripeInvoice;
  "stripe/lib/stripeInvoiceBillingUrls": typeof stripe_lib_stripeInvoiceBillingUrls;
  "stripe/lib/stripeInvoices": typeof stripe_lib_stripeInvoices;
  "stripe/services/bookingCustomInvoice": typeof stripe_services_bookingCustomInvoice;
  "stripe/services/editInvoiceBilling": typeof stripe_services_editInvoiceBilling;
  "stripe/services/editInvoiceSend": typeof stripe_services_editInvoiceSend;
  "stripe/services/editInvoiceValidators": typeof stripe_services_editInvoiceValidators;
  "stripe/services/invoicePdf": typeof stripe_services_invoicePdf;
  "stripe/services/stripeCheckoutSession": typeof stripe_services_stripeCheckoutSession;
  "stripe/services/stripeInvoiceMutations": typeof stripe_services_stripeInvoiceMutations;
  "stripe/services/stripeInvoicePayment": typeof stripe_services_stripeInvoicePayment;
  "stripe/services/stripeInvoiceSend": typeof stripe_services_stripeInvoiceSend;
  "stripe/services/stripeInvoices": typeof stripe_services_stripeInvoices;
  "stripe/stripe": typeof stripe_stripe;
  "stripe/stripeInvoices": typeof stripe_stripeInvoices;
  "stripe/stripeInvoicing": typeof stripe_stripeInvoicing;
  "tests/insertDocumentDefaults": typeof tests_insertDocumentDefaults;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  rateLimiter: import("@convex-dev/rate-limiter/_generated/component.js").ComponentApi<"rateLimiter">;
};
