/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as booking_confirmation from "../booking/confirmation.js";
import type * as booking_lib_addonQuantities from "../booking/lib/addonQuantities.js";
import type * as booking_lib_confirmationActionBoundaries from "../booking/lib/confirmationActionBoundaries.js";
import type * as booking_lib_confirmationClaim from "../booking/lib/confirmationClaim.js";
import type * as booking_lib_confirmationSave from "../booking/lib/confirmationSave.js";
import type * as booking_lib_confirmationSessionPatches from "../booking/lib/confirmationSessionPatches.js";
import type * as booking_lib_formFields from "../booking/lib/formFields.js";
import type * as booking_lib_invoicePdfRender from "../booking/lib/invoicePdfRender.js";
import type * as booking_lib_receipt from "../booking/lib/receipt.js";
import type * as booking_lib_receiptEmailPipeline from "../booking/lib/receiptEmailPipeline.js";
import type * as booking_lib_settings from "../booking/lib/settings.js";
import type * as booking_lib_submission from "../booking/lib/submission.js";
import type * as booking_services_checkout from "../booking/services/checkout.js";
import type * as booking_services_claimedSession from "../booking/services/claimedSession.js";
import type * as booking_services_confirmation from "../booking/services/confirmation.js";
import type * as booking_services_confirmationMutations from "../booking/services/confirmationMutations.js";
import type * as booking_services_confirmationWorkflow from "../booking/services/confirmationWorkflow.js";
import type * as booking_services_formValidators from "../booking/services/formValidators.js";
import type * as booking_services_receiptEmails from "../booking/services/receiptEmails.js";
import type * as booking_services_receiptResend from "../booking/services/receiptResend.js";
import type * as booking_services_sessionReminderEmail from "../booking/services/sessionReminderEmail.js";
import type * as booking_services_settings from "../booking/services/settings.js";
import type * as booking_services_submission from "../booking/services/submission.js";
import type * as booking_settings from "../booking/settings.js";
import type * as crons from "../crons.js";
import type * as devSeed from "../devSeed.js";
import type * as drive_drive from "../drive/drive.js";
import type * as drive_lib_driveBookingDriveClient from "../drive/lib/driveBookingDriveClient.js";
import type * as drive_lib_driveClientAccess from "../drive/lib/driveClientAccess.js";
import type * as drive_lib_driveEditor from "../drive/lib/driveEditor.js";
import type * as drive_lib_driveFolderTreeValidation from "../drive/lib/driveFolderTreeValidation.js";
import type * as drive_lib_driveFolders from "../drive/lib/driveFolders.js";
import type * as drive_lib_driveLookup from "../drive/lib/driveLookup.js";
import type * as drive_lib_driveScheduling from "../drive/lib/driveScheduling.js";
import type * as drive_lib_driveSetupLoad from "../drive/lib/driveSetupLoad.js";
import type * as drive_lib_driveStatus from "../drive/lib/driveStatus.js";
import type * as drive_lib_editorRetirement from "../drive/lib/editorRetirement.js";
import type * as drive_lib_googleDrive from "../drive/lib/googleDrive.js";
import type * as drive_lib_sessionFolders_allocateNumbers from "../drive/lib/sessionFolders/allocateNumbers.js";
import type * as drive_lib_sessionFolders_cancelCleanup from "../drive/lib/sessionFolders/cancelCleanup.js";
import type * as drive_lib_sessionFolders_clearSessionRecords from "../drive/lib/sessionFolders/clearSessionRecords.js";
import type * as drive_lib_sessionFolders_driveSetupInfo from "../drive/lib/sessionFolders/driveSetupInfo.js";
import type * as drive_lib_sessionFolders_resolveFolderNames from "../drive/lib/sessionFolders/resolveFolderNames.js";
import type * as drive_services_cleanupCancelledSessionDrive from "../drive/services/cleanupCancelledSessionDrive.js";
import type * as drive_services_clientAccess from "../drive/services/clientAccess.js";
import type * as drive_services_clientDrivePermissions from "../drive/services/clientDrivePermissions.js";
import type * as drive_services_drive from "../drive/services/drive.js";
import type * as drive_services_driveClientPermissions from "../drive/services/driveClientPermissions.js";
import type * as drive_services_driveEditorPermissions from "../drive/services/driveEditorPermissions.js";
import type * as drive_services_driveSetupQuery from "../drive/services/driveSetupQuery.js";
import type * as drive_services_driveStatusQuery from "../drive/services/driveStatusQuery.js";
import type * as drive_services_editorDrivePermissions from "../drive/services/editorDrivePermissions.js";
import type * as drive_services_editorPermissions from "../drive/services/editorPermissions.js";
import type * as drive_services_editorRetirement from "../drive/services/editorRetirement.js";
import type * as drive_services_ensureSessionDriveFolderClientSteps from "../drive/services/ensureSessionDriveFolderClientSteps.js";
import type * as drive_services_ensureSessionDriveFolderHelpers from "../drive/services/ensureSessionDriveFolderHelpers.js";
import type * as drive_services_ensureSessionDriveFolderSessionSteps from "../drive/services/ensureSessionDriveFolderSessionSteps.js";
import type * as drive_services_ensureSessionDriveFolderSteps from "../drive/services/ensureSessionDriveFolderSteps.js";
import type * as drive_services_ensureSessionDriveFolders from "../drive/services/ensureSessionDriveFolders.js";
import type * as drive_services_googleDriveFolderTree from "../drive/services/googleDriveFolderTree.js";
import type * as drive_services_setup from "../drive/services/setup.js";
import type * as editor_deliverablesEmail from "../editor/deliverablesEmail.js";
import type * as editor_deliverablesReviewEmail from "../editor/deliverablesReviewEmail.js";
import type * as editor_lib_deliverablesReviewNotification from "../editor/lib/deliverablesReviewNotification.js";
import type * as editor_lib_editorAccess from "../editor/lib/editorAccess.js";
import type * as editor_lib_editorAssignments from "../editor/lib/editorAssignments.js";
import type * as editor_lib_editorSessions from "../editor/lib/editorSessions.js";
import type * as editor_services_deliverablesEmail from "../editor/services/deliverablesEmail.js";
import type * as editor_services_deliverablesReviewReadyEmail from "../editor/services/deliverablesReviewReadyEmail.js";
import type * as editor_services_loadSessionForDeliverables from "../editor/services/loadSessionForDeliverables.js";
import type * as editor_services_sessionEditStatus from "../editor/services/sessionEditStatus.js";
import type * as email_receiptEmails from "../email/receiptEmails.js";
import type * as email_services_bookingCustomerEmails from "../email/services/bookingCustomerEmails.js";
import type * as email_services_hostBookingEmails from "../email/services/hostBookingEmails.js";
import type * as email_services_packageReminderEmails from "../email/services/packageReminderEmails.js";
import type * as email_services_templateEmails from "../email/services/templateEmails.js";
import type * as employees_admin from "../employees/admin.js";
import type * as employees_invitations from "../employees/invitations.js";
import type * as employees_services_employeeInvitation from "../employees/services/employeeInvitation.js";
import type * as employees_services_employeeManagement from "../employees/services/employeeManagement.js";
import type * as env from "../env.js";
import type * as feedback_lib_feedback from "../feedback/lib/feedback.js";
import type * as feedback_public from "../feedback/public.js";
import type * as feedback_services_feedbackEmail from "../feedback/services/feedbackEmail.js";
import type * as feedback_services_submitFeedback from "../feedback/services/submitFeedback.js";
import type * as googleCalendar_calendar from "../googleCalendar/calendar.js";
import type * as googleCalendar_lib_googleAuth from "../googleCalendar/lib/googleAuth.js";
import type * as googleCalendar_lib_googleCalendarAvailability from "../googleCalendar/lib/googleCalendarAvailability.js";
import type * as googleCalendar_lib_googleCalendarClient from "../googleCalendar/lib/googleCalendarClient.js";
import type * as googleCalendar_lib_googleCalendarErrors from "../googleCalendar/lib/googleCalendarErrors.js";
import type * as googleCalendar_lib_googleCalendarEventCalls from "../googleCalendar/lib/googleCalendarEventCalls.js";
import type * as googleCalendar_lib_packageDetails from "../googleCalendar/lib/packageDetails.js";
import type * as googleCalendar_services_adminUpdate from "../googleCalendar/services/adminUpdate.js";
import type * as googleCalendar_services_calendar from "../googleCalendar/services/calendar.js";
import type * as googleCalendar_services_calendarAvailability from "../googleCalendar/services/calendarAvailability.js";
import type * as googleCalendar_services_calendarAvailabilityLoad from "../googleCalendar/services/calendarAvailabilityLoad.js";
import type * as googleCalendar_services_calendarEvent from "../googleCalendar/services/calendarEvent.js";
import type * as googleCalendar_services_calendarEventOrchestrationSteps from "../googleCalendar/services/calendarEventOrchestrationSteps.js";
import type * as googleCalendar_services_calendarReschedule from "../googleCalendar/services/calendarReschedule.js";
import type * as googleCalendar_services_calendarTime from "../googleCalendar/services/calendarTime.js";
import type * as googleCalendar_services_calendarTimingSync from "../googleCalendar/services/calendarTimingSync.js";
import type * as googleCalendar_services_cancelBookingFromAdmin from "../googleCalendar/services/cancelBookingFromAdmin.js";
import type * as googleCalendar_services_packageAvailability from "../googleCalendar/services/packageAvailability.js";
import type * as googleCalendar_services_packageDetails from "../googleCalendar/services/packageDetails.js";
import type * as googleCalendar_services_packageScheduling from "../googleCalendar/services/packageScheduling.js";
import type * as http from "../http.js";
import type * as packages_adjustmentInvoices from "../packages/adjustmentInvoices.js";
import type * as packages_adjustments from "../packages/adjustments.js";
import type * as packages_admin from "../packages/admin.js";
import type * as packages_checkout from "../packages/checkout.js";
import type * as packages_checkoutCompletionHandlers from "../packages/checkoutCompletionHandlers.js";
import type * as packages_lib_adjustmentInvoicePayment from "../packages/lib/adjustmentInvoicePayment.js";
import type * as packages_lib_adjustmentJobs from "../packages/lib/adjustmentJobs.js";
import type * as packages_lib_adjustmentScheduling from "../packages/lib/adjustmentScheduling.js";
import type * as packages_lib_adjustments from "../packages/lib/adjustments.js";
import type * as packages_lib_archive from "../packages/lib/archive.js";
import type * as packages_lib_bookingsReceiptSync from "../packages/lib/bookingsReceiptSync.js";
import type * as packages_lib_checkout from "../packages/lib/checkout.js";
import type * as packages_lib_checkoutClaim from "../packages/lib/checkoutClaim.js";
import type * as packages_lib_lookup from "../packages/lib/lookup.js";
import type * as packages_lib_paidLifecycle from "../packages/lib/paidLifecycle.js";
import type * as packages_lib_payment from "../packages/lib/payment.js";
import type * as packages_lib_reminderDb from "../packages/lib/reminderDb.js";
import type * as packages_lib_reminders from "../packages/lib/reminders.js";
import type * as packages_lib_scheduling from "../packages/lib/scheduling.js";
import type * as packages_lib_schedulingActionBoundaries from "../packages/lib/schedulingActionBoundaries.js";
import type * as packages_lib_sessionBookings from "../packages/lib/sessionBookings.js";
import type * as packages_lib_sessionCapacity from "../packages/lib/sessionCapacity.js";
import type * as packages_lib_tokenView from "../packages/lib/tokenView.js";
import type * as packages_lib_updates from "../packages/lib/updates.js";
import type * as packages_payment from "../packages/payment.js";
import type * as packages_reminders from "../packages/reminders.js";
import type * as packages_scheduling from "../packages/scheduling.js";
import type * as packages_schedulingCalendar from "../packages/schedulingCalendar.js";
import type * as packages_services_adjustmentCron from "../packages/services/adjustmentCron.js";
import type * as packages_services_adjustmentInvoiceEmail from "../packages/services/adjustmentInvoiceEmail.js";
import type * as packages_services_adjustmentInvoicePayment from "../packages/services/adjustmentInvoicePayment.js";
import type * as packages_services_adjustmentInvoiceSend from "../packages/services/adjustmentInvoiceSend.js";
import type * as packages_services_adjustments from "../packages/services/adjustments.js";
import type * as packages_services_adminMutations from "../packages/services/adminMutations.js";
import type * as packages_services_adminQueries from "../packages/services/adminQueries.js";
import type * as packages_services_archive from "../packages/services/archive.js";
import type * as packages_services_bookingsReceiptSync from "../packages/services/bookingsReceiptSync.js";
import type * as packages_services_checkoutCompletion from "../packages/services/checkoutCompletion.js";
import type * as packages_services_checkoutMutations from "../packages/services/checkoutMutations.js";
import type * as packages_services_checkoutSession from "../packages/services/checkoutSession.js";
import type * as packages_services_claimedCheckoutCompletion from "../packages/services/claimedCheckoutCompletion.js";
import type * as packages_services_emailAttempts from "../packages/services/emailAttempts.js";
import type * as packages_services_instagram from "../packages/services/instagram.js";
import type * as packages_services_lookup from "../packages/services/lookup.js";
import type * as packages_services_paid from "../packages/services/paid.js";
import type * as packages_services_paidEmailResend from "../packages/services/paidEmailResend.js";
import type * as packages_services_paidEmailSend from "../packages/services/paidEmailSend.js";
import type * as packages_services_pending from "../packages/services/pending.js";
import type * as packages_services_reminderMutations from "../packages/services/reminderMutations.js";
import type * as packages_services_reminders from "../packages/services/reminders.js";
import type * as packages_services_sessionCancel from "../packages/services/sessionCancel.js";
import type * as packages_services_sessionMutations from "../packages/services/sessionMutations.js";
import type * as packages_services_sessionScheduling from "../packages/services/sessionScheduling.js";
import type * as packages_services_sessionSchedulingTypes from "../packages/services/sessionSchedulingTypes.js";
import type * as packages_services_tokenScheduling from "../packages/services/tokenScheduling.js";
import type * as packages_services_tokens from "../packages/services/tokens.js";
import type * as sessions_admin from "../sessions/admin.js";
import type * as sessions_checkout from "../sessions/checkout.js";
import type * as sessions_drive from "../sessions/drive.js";
import type * as sessions_lib_adminEdit from "../sessions/lib/adminEdit.js";
import type * as sessions_lib_archive from "../sessions/lib/archive.js";
import type * as sessions_lib_calendarActionBoundaries from "../sessions/lib/calendarActionBoundaries.js";
import type * as sessions_lib_calendarEventPayload from "../sessions/lib/calendarEventPayload.js";
import type * as sessions_lib_calendarTime from "../sessions/lib/calendarTime.js";
import type * as sessions_lib_checkout from "../sessions/lib/checkout.js";
import type * as sessions_lib_lookup from "../sessions/lib/lookup.js";
import type * as sessions_lib_pendingCheckoutSession from "../sessions/lib/pendingCheckoutSession.js";
import type * as sessions_lib_reminderDb from "../sessions/lib/reminderDb.js";
import type * as sessions_lib_rescheduleLinks from "../sessions/lib/rescheduleLinks.js";
import type * as sessions_lib_reservationDb from "../sessions/lib/reservationDb.js";
import type * as sessions_lib_reservations from "../sessions/lib/reservations.js";
import type * as sessions_lib_savePatch from "../sessions/lib/savePatch.js";
import type * as sessions_lib_schedulingArgs from "../sessions/lib/schedulingArgs.js";
import type * as sessions_lib_schedulingSave from "../sessions/lib/schedulingSave.js";
import type * as sessions_lib_slotReservationAction from "../sessions/lib/slotReservationAction.js";
import type * as sessions_reminders from "../sessions/reminders.js";
import type * as sessions_reschedule from "../sessions/reschedule.js";
import type * as sessions_scheduling from "../sessions/scheduling.js";
import type * as sessions_services_adminList from "../sessions/services/adminList.js";
import type * as sessions_services_archive from "../sessions/services/archive.js";
import type * as sessions_services_deliverables from "../sessions/services/deliverables.js";
import type * as sessions_services_editor from "../sessions/services/editor.js";
import type * as sessions_services_editorAssignment from "../sessions/services/editorAssignment.js";
import type * as sessions_services_lookup from "../sessions/services/lookup.js";
import type * as sessions_services_mutations from "../sessions/services/mutations.js";
import type * as sessions_services_queries from "../sessions/services/queries.js";
import type * as sessions_services_reminderCron from "../sessions/services/reminderCron.js";
import type * as sessions_services_reminderMutations from "../sessions/services/reminderMutations.js";
import type * as sessions_services_reschedule from "../sessions/services/reschedule.js";
import type * as sessions_services_rescheduleEmails from "../sessions/services/rescheduleEmails.js";
import type * as sessions_services_reservationValidators from "../sessions/services/reservationValidators.js";
import type * as sessions_services_reservations from "../sessions/services/reservations.js";
import type * as sessions_services_schedulingSave from "../sessions/services/schedulingSave.js";
import type * as shared_auth from "../shared/auth.js";
import type * as shared_lib_adminSearch_adminListSearchPage from "../shared/lib/adminSearch/adminListSearchPage.js";
import type * as shared_lib_adminSearch_adminSearchBlob from "../shared/lib/adminSearch/adminSearchBlob.js";
import type * as shared_lib_adminSearch_adminSearchDateParse from "../shared/lib/adminSearch/adminSearchDateParse.js";
import type * as shared_lib_adminSearch_adminSearchPrefixFilters from "../shared/lib/adminSearch/adminSearchPrefixFilters.js";
import type * as shared_lib_adminSearch_adminSearchQuery from "../shared/lib/adminSearch/adminSearchQuery.js";
import type * as shared_lib_archiveState from "../shared/lib/archiveState.js";
import type * as shared_lib_auth from "../shared/lib/auth.js";
import type * as shared_lib_clerkInvitations from "../shared/lib/clerkInvitations.js";
import type * as shared_lib_contactNormalization from "../shared/lib/contactNormalization.js";
import type * as shared_lib_crypto_bytesToHex from "../shared/lib/crypto/bytesToHex.js";
import type * as shared_lib_driveValidators from "../shared/lib/driveValidators.js";
import type * as shared_lib_email_emailDomain from "../shared/lib/email/emailDomain.js";
import type * as shared_lib_email_emailRenders from "../shared/lib/email/emailRenders.js";
import type * as shared_lib_email_emailSend from "../shared/lib/email/emailSend.js";
import type * as shared_lib_listAdminPackages from "../shared/lib/listAdminPackages.js";
import type * as shared_lib_listAdminSessions from "../shared/lib/listAdminSessions.js";
import type * as shared_lib_rateLimits from "../shared/lib/rateLimits.js";
import type * as shared_lib_reminderScheduleTime from "../shared/lib/reminderScheduleTime.js";
import type * as shared_lib_result from "../shared/lib/result.js";
import type * as shared_lib_tests_testIds from "../shared/lib/tests/testIds.js";
import type * as shared_services_auth from "../shared/services/auth.js";
import type * as shared_services_authPermissions from "../shared/services/authPermissions.js";
import type * as shared_services_requirePermissionActions from "../shared/services/requirePermissionActions.js";
import type * as stripe_checkout from "../stripe/checkout.js";
import type * as stripe_customInvoices from "../stripe/customInvoices.js";
import type * as stripe_editInvoices from "../stripe/editInvoices.js";
import type * as stripe_editInvoicing from "../stripe/editInvoicing.js";
import type * as stripe_invoiceRecords from "../stripe/invoiceRecords.js";
import type * as stripe_invoices from "../stripe/invoices.js";
import type * as stripe_invoicing from "../stripe/invoicing.js";
import type * as stripe_lib_adjustmentInvoice from "../stripe/lib/adjustmentInvoice.js";
import type * as stripe_lib_apiErrors from "../stripe/lib/apiErrors.js";
import type * as stripe_lib_checkoutSession from "../stripe/lib/checkoutSession.js";
import type * as stripe_lib_client from "../stripe/lib/client.js";
import type * as stripe_lib_customInvoices from "../stripe/lib/customInvoices.js";
import type * as stripe_lib_editInvoiceBilling from "../stripe/lib/editInvoiceBilling.js";
import type * as stripe_lib_editInvoiceDb from "../stripe/lib/editInvoiceDb.js";
import type * as stripe_lib_editInvoiceLineItems from "../stripe/lib/editInvoiceLineItems.js";
import type * as stripe_lib_editInvoiceRequest from "../stripe/lib/editInvoiceRequest.js";
import type * as stripe_lib_editInvoiceStripe from "../stripe/lib/editInvoiceStripe.js";
import type * as stripe_lib_invoice from "../stripe/lib/invoice.js";
import type * as stripe_lib_invoiceBillingUrls from "../stripe/lib/invoiceBillingUrls.js";
import type * as stripe_lib_invoiceDownloads from "../stripe/lib/invoiceDownloads.js";
import type * as stripe_lib_invoices from "../stripe/lib/invoices.js";
import type * as stripe_services_bookingCustomInvoice from "../stripe/services/bookingCustomInvoice.js";
import type * as stripe_services_checkoutSession from "../stripe/services/checkoutSession.js";
import type * as stripe_services_editInvoiceBilling from "../stripe/services/editInvoiceBilling.js";
import type * as stripe_services_editInvoiceSend from "../stripe/services/editInvoiceSend.js";
import type * as stripe_services_editInvoiceValidators from "../stripe/services/editInvoiceValidators.js";
import type * as stripe_services_invoiceMutations from "../stripe/services/invoiceMutations.js";
import type * as stripe_services_invoicePayment from "../stripe/services/invoicePayment.js";
import type * as stripe_services_invoicePdf from "../stripe/services/invoicePdf.js";
import type * as stripe_services_invoiceSend from "../stripe/services/invoiceSend.js";
import type * as stripe_services_invoices from "../stripe/services/invoices.js";
import type * as tests_insertDocumentDefaults from "../tests/insertDocumentDefaults.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "booking/confirmation": typeof booking_confirmation;
  "booking/lib/addonQuantities": typeof booking_lib_addonQuantities;
  "booking/lib/confirmationActionBoundaries": typeof booking_lib_confirmationActionBoundaries;
  "booking/lib/confirmationClaim": typeof booking_lib_confirmationClaim;
  "booking/lib/confirmationSave": typeof booking_lib_confirmationSave;
  "booking/lib/confirmationSessionPatches": typeof booking_lib_confirmationSessionPatches;
  "booking/lib/formFields": typeof booking_lib_formFields;
  "booking/lib/invoicePdfRender": typeof booking_lib_invoicePdfRender;
  "booking/lib/receipt": typeof booking_lib_receipt;
  "booking/lib/receiptEmailPipeline": typeof booking_lib_receiptEmailPipeline;
  "booking/lib/settings": typeof booking_lib_settings;
  "booking/lib/submission": typeof booking_lib_submission;
  "booking/services/checkout": typeof booking_services_checkout;
  "booking/services/claimedSession": typeof booking_services_claimedSession;
  "booking/services/confirmation": typeof booking_services_confirmation;
  "booking/services/confirmationMutations": typeof booking_services_confirmationMutations;
  "booking/services/confirmationWorkflow": typeof booking_services_confirmationWorkflow;
  "booking/services/formValidators": typeof booking_services_formValidators;
  "booking/services/receiptEmails": typeof booking_services_receiptEmails;
  "booking/services/receiptResend": typeof booking_services_receiptResend;
  "booking/services/sessionReminderEmail": typeof booking_services_sessionReminderEmail;
  "booking/services/settings": typeof booking_services_settings;
  "booking/services/submission": typeof booking_services_submission;
  "booking/settings": typeof booking_settings;
  crons: typeof crons;
  devSeed: typeof devSeed;
  "drive/drive": typeof drive_drive;
  "drive/lib/driveBookingDriveClient": typeof drive_lib_driveBookingDriveClient;
  "drive/lib/driveClientAccess": typeof drive_lib_driveClientAccess;
  "drive/lib/driveEditor": typeof drive_lib_driveEditor;
  "drive/lib/driveFolderTreeValidation": typeof drive_lib_driveFolderTreeValidation;
  "drive/lib/driveFolders": typeof drive_lib_driveFolders;
  "drive/lib/driveLookup": typeof drive_lib_driveLookup;
  "drive/lib/driveScheduling": typeof drive_lib_driveScheduling;
  "drive/lib/driveSetupLoad": typeof drive_lib_driveSetupLoad;
  "drive/lib/driveStatus": typeof drive_lib_driveStatus;
  "drive/lib/editorRetirement": typeof drive_lib_editorRetirement;
  "drive/lib/googleDrive": typeof drive_lib_googleDrive;
  "drive/lib/sessionFolders/allocateNumbers": typeof drive_lib_sessionFolders_allocateNumbers;
  "drive/lib/sessionFolders/cancelCleanup": typeof drive_lib_sessionFolders_cancelCleanup;
  "drive/lib/sessionFolders/clearSessionRecords": typeof drive_lib_sessionFolders_clearSessionRecords;
  "drive/lib/sessionFolders/driveSetupInfo": typeof drive_lib_sessionFolders_driveSetupInfo;
  "drive/lib/sessionFolders/resolveFolderNames": typeof drive_lib_sessionFolders_resolveFolderNames;
  "drive/services/cleanupCancelledSessionDrive": typeof drive_services_cleanupCancelledSessionDrive;
  "drive/services/clientAccess": typeof drive_services_clientAccess;
  "drive/services/clientDrivePermissions": typeof drive_services_clientDrivePermissions;
  "drive/services/drive": typeof drive_services_drive;
  "drive/services/driveClientPermissions": typeof drive_services_driveClientPermissions;
  "drive/services/driveEditorPermissions": typeof drive_services_driveEditorPermissions;
  "drive/services/driveSetupQuery": typeof drive_services_driveSetupQuery;
  "drive/services/driveStatusQuery": typeof drive_services_driveStatusQuery;
  "drive/services/editorDrivePermissions": typeof drive_services_editorDrivePermissions;
  "drive/services/editorPermissions": typeof drive_services_editorPermissions;
  "drive/services/editorRetirement": typeof drive_services_editorRetirement;
  "drive/services/ensureSessionDriveFolderClientSteps": typeof drive_services_ensureSessionDriveFolderClientSteps;
  "drive/services/ensureSessionDriveFolderHelpers": typeof drive_services_ensureSessionDriveFolderHelpers;
  "drive/services/ensureSessionDriveFolderSessionSteps": typeof drive_services_ensureSessionDriveFolderSessionSteps;
  "drive/services/ensureSessionDriveFolderSteps": typeof drive_services_ensureSessionDriveFolderSteps;
  "drive/services/ensureSessionDriveFolders": typeof drive_services_ensureSessionDriveFolders;
  "drive/services/googleDriveFolderTree": typeof drive_services_googleDriveFolderTree;
  "drive/services/setup": typeof drive_services_setup;
  "editor/deliverablesEmail": typeof editor_deliverablesEmail;
  "editor/deliverablesReviewEmail": typeof editor_deliverablesReviewEmail;
  "editor/lib/deliverablesReviewNotification": typeof editor_lib_deliverablesReviewNotification;
  "editor/lib/editorAccess": typeof editor_lib_editorAccess;
  "editor/lib/editorAssignments": typeof editor_lib_editorAssignments;
  "editor/lib/editorSessions": typeof editor_lib_editorSessions;
  "editor/services/deliverablesEmail": typeof editor_services_deliverablesEmail;
  "editor/services/deliverablesReviewReadyEmail": typeof editor_services_deliverablesReviewReadyEmail;
  "editor/services/loadSessionForDeliverables": typeof editor_services_loadSessionForDeliverables;
  "editor/services/sessionEditStatus": typeof editor_services_sessionEditStatus;
  "email/receiptEmails": typeof email_receiptEmails;
  "email/services/bookingCustomerEmails": typeof email_services_bookingCustomerEmails;
  "email/services/hostBookingEmails": typeof email_services_hostBookingEmails;
  "email/services/packageReminderEmails": typeof email_services_packageReminderEmails;
  "email/services/templateEmails": typeof email_services_templateEmails;
  "employees/admin": typeof employees_admin;
  "employees/invitations": typeof employees_invitations;
  "employees/services/employeeInvitation": typeof employees_services_employeeInvitation;
  "employees/services/employeeManagement": typeof employees_services_employeeManagement;
  env: typeof env;
  "feedback/lib/feedback": typeof feedback_lib_feedback;
  "feedback/public": typeof feedback_public;
  "feedback/services/feedbackEmail": typeof feedback_services_feedbackEmail;
  "feedback/services/submitFeedback": typeof feedback_services_submitFeedback;
  "googleCalendar/calendar": typeof googleCalendar_calendar;
  "googleCalendar/lib/googleAuth": typeof googleCalendar_lib_googleAuth;
  "googleCalendar/lib/googleCalendarAvailability": typeof googleCalendar_lib_googleCalendarAvailability;
  "googleCalendar/lib/googleCalendarClient": typeof googleCalendar_lib_googleCalendarClient;
  "googleCalendar/lib/googleCalendarErrors": typeof googleCalendar_lib_googleCalendarErrors;
  "googleCalendar/lib/googleCalendarEventCalls": typeof googleCalendar_lib_googleCalendarEventCalls;
  "googleCalendar/lib/packageDetails": typeof googleCalendar_lib_packageDetails;
  "googleCalendar/services/adminUpdate": typeof googleCalendar_services_adminUpdate;
  "googleCalendar/services/calendar": typeof googleCalendar_services_calendar;
  "googleCalendar/services/calendarAvailability": typeof googleCalendar_services_calendarAvailability;
  "googleCalendar/services/calendarAvailabilityLoad": typeof googleCalendar_services_calendarAvailabilityLoad;
  "googleCalendar/services/calendarEvent": typeof googleCalendar_services_calendarEvent;
  "googleCalendar/services/calendarEventOrchestrationSteps": typeof googleCalendar_services_calendarEventOrchestrationSteps;
  "googleCalendar/services/calendarReschedule": typeof googleCalendar_services_calendarReschedule;
  "googleCalendar/services/calendarTime": typeof googleCalendar_services_calendarTime;
  "googleCalendar/services/calendarTimingSync": typeof googleCalendar_services_calendarTimingSync;
  "googleCalendar/services/cancelBookingFromAdmin": typeof googleCalendar_services_cancelBookingFromAdmin;
  "googleCalendar/services/packageAvailability": typeof googleCalendar_services_packageAvailability;
  "googleCalendar/services/packageDetails": typeof googleCalendar_services_packageDetails;
  "googleCalendar/services/packageScheduling": typeof googleCalendar_services_packageScheduling;
  http: typeof http;
  "packages/adjustmentInvoices": typeof packages_adjustmentInvoices;
  "packages/adjustments": typeof packages_adjustments;
  "packages/admin": typeof packages_admin;
  "packages/checkout": typeof packages_checkout;
  "packages/checkoutCompletionHandlers": typeof packages_checkoutCompletionHandlers;
  "packages/lib/adjustmentInvoicePayment": typeof packages_lib_adjustmentInvoicePayment;
  "packages/lib/adjustmentJobs": typeof packages_lib_adjustmentJobs;
  "packages/lib/adjustmentScheduling": typeof packages_lib_adjustmentScheduling;
  "packages/lib/adjustments": typeof packages_lib_adjustments;
  "packages/lib/archive": typeof packages_lib_archive;
  "packages/lib/bookingsReceiptSync": typeof packages_lib_bookingsReceiptSync;
  "packages/lib/checkout": typeof packages_lib_checkout;
  "packages/lib/checkoutClaim": typeof packages_lib_checkoutClaim;
  "packages/lib/lookup": typeof packages_lib_lookup;
  "packages/lib/paidLifecycle": typeof packages_lib_paidLifecycle;
  "packages/lib/payment": typeof packages_lib_payment;
  "packages/lib/reminderDb": typeof packages_lib_reminderDb;
  "packages/lib/reminders": typeof packages_lib_reminders;
  "packages/lib/scheduling": typeof packages_lib_scheduling;
  "packages/lib/schedulingActionBoundaries": typeof packages_lib_schedulingActionBoundaries;
  "packages/lib/sessionBookings": typeof packages_lib_sessionBookings;
  "packages/lib/sessionCapacity": typeof packages_lib_sessionCapacity;
  "packages/lib/tokenView": typeof packages_lib_tokenView;
  "packages/lib/updates": typeof packages_lib_updates;
  "packages/payment": typeof packages_payment;
  "packages/reminders": typeof packages_reminders;
  "packages/scheduling": typeof packages_scheduling;
  "packages/schedulingCalendar": typeof packages_schedulingCalendar;
  "packages/services/adjustmentCron": typeof packages_services_adjustmentCron;
  "packages/services/adjustmentInvoiceEmail": typeof packages_services_adjustmentInvoiceEmail;
  "packages/services/adjustmentInvoicePayment": typeof packages_services_adjustmentInvoicePayment;
  "packages/services/adjustmentInvoiceSend": typeof packages_services_adjustmentInvoiceSend;
  "packages/services/adjustments": typeof packages_services_adjustments;
  "packages/services/adminMutations": typeof packages_services_adminMutations;
  "packages/services/adminQueries": typeof packages_services_adminQueries;
  "packages/services/archive": typeof packages_services_archive;
  "packages/services/bookingsReceiptSync": typeof packages_services_bookingsReceiptSync;
  "packages/services/checkoutCompletion": typeof packages_services_checkoutCompletion;
  "packages/services/checkoutMutations": typeof packages_services_checkoutMutations;
  "packages/services/checkoutSession": typeof packages_services_checkoutSession;
  "packages/services/claimedCheckoutCompletion": typeof packages_services_claimedCheckoutCompletion;
  "packages/services/emailAttempts": typeof packages_services_emailAttempts;
  "packages/services/instagram": typeof packages_services_instagram;
  "packages/services/lookup": typeof packages_services_lookup;
  "packages/services/paid": typeof packages_services_paid;
  "packages/services/paidEmailResend": typeof packages_services_paidEmailResend;
  "packages/services/paidEmailSend": typeof packages_services_paidEmailSend;
  "packages/services/pending": typeof packages_services_pending;
  "packages/services/reminderMutations": typeof packages_services_reminderMutations;
  "packages/services/reminders": typeof packages_services_reminders;
  "packages/services/sessionCancel": typeof packages_services_sessionCancel;
  "packages/services/sessionMutations": typeof packages_services_sessionMutations;
  "packages/services/sessionScheduling": typeof packages_services_sessionScheduling;
  "packages/services/sessionSchedulingTypes": typeof packages_services_sessionSchedulingTypes;
  "packages/services/tokenScheduling": typeof packages_services_tokenScheduling;
  "packages/services/tokens": typeof packages_services_tokens;
  "sessions/admin": typeof sessions_admin;
  "sessions/checkout": typeof sessions_checkout;
  "sessions/drive": typeof sessions_drive;
  "sessions/lib/adminEdit": typeof sessions_lib_adminEdit;
  "sessions/lib/archive": typeof sessions_lib_archive;
  "sessions/lib/calendarActionBoundaries": typeof sessions_lib_calendarActionBoundaries;
  "sessions/lib/calendarEventPayload": typeof sessions_lib_calendarEventPayload;
  "sessions/lib/calendarTime": typeof sessions_lib_calendarTime;
  "sessions/lib/checkout": typeof sessions_lib_checkout;
  "sessions/lib/lookup": typeof sessions_lib_lookup;
  "sessions/lib/pendingCheckoutSession": typeof sessions_lib_pendingCheckoutSession;
  "sessions/lib/reminderDb": typeof sessions_lib_reminderDb;
  "sessions/lib/rescheduleLinks": typeof sessions_lib_rescheduleLinks;
  "sessions/lib/reservationDb": typeof sessions_lib_reservationDb;
  "sessions/lib/reservations": typeof sessions_lib_reservations;
  "sessions/lib/savePatch": typeof sessions_lib_savePatch;
  "sessions/lib/schedulingArgs": typeof sessions_lib_schedulingArgs;
  "sessions/lib/schedulingSave": typeof sessions_lib_schedulingSave;
  "sessions/lib/slotReservationAction": typeof sessions_lib_slotReservationAction;
  "sessions/reminders": typeof sessions_reminders;
  "sessions/reschedule": typeof sessions_reschedule;
  "sessions/scheduling": typeof sessions_scheduling;
  "sessions/services/adminList": typeof sessions_services_adminList;
  "sessions/services/archive": typeof sessions_services_archive;
  "sessions/services/deliverables": typeof sessions_services_deliverables;
  "sessions/services/editor": typeof sessions_services_editor;
  "sessions/services/editorAssignment": typeof sessions_services_editorAssignment;
  "sessions/services/lookup": typeof sessions_services_lookup;
  "sessions/services/mutations": typeof sessions_services_mutations;
  "sessions/services/queries": typeof sessions_services_queries;
  "sessions/services/reminderCron": typeof sessions_services_reminderCron;
  "sessions/services/reminderMutations": typeof sessions_services_reminderMutations;
  "sessions/services/reschedule": typeof sessions_services_reschedule;
  "sessions/services/rescheduleEmails": typeof sessions_services_rescheduleEmails;
  "sessions/services/reservationValidators": typeof sessions_services_reservationValidators;
  "sessions/services/reservations": typeof sessions_services_reservations;
  "sessions/services/schedulingSave": typeof sessions_services_schedulingSave;
  "shared/auth": typeof shared_auth;
  "shared/lib/adminSearch/adminListSearchPage": typeof shared_lib_adminSearch_adminListSearchPage;
  "shared/lib/adminSearch/adminSearchBlob": typeof shared_lib_adminSearch_adminSearchBlob;
  "shared/lib/adminSearch/adminSearchDateParse": typeof shared_lib_adminSearch_adminSearchDateParse;
  "shared/lib/adminSearch/adminSearchPrefixFilters": typeof shared_lib_adminSearch_adminSearchPrefixFilters;
  "shared/lib/adminSearch/adminSearchQuery": typeof shared_lib_adminSearch_adminSearchQuery;
  "shared/lib/archiveState": typeof shared_lib_archiveState;
  "shared/lib/auth": typeof shared_lib_auth;
  "shared/lib/clerkInvitations": typeof shared_lib_clerkInvitations;
  "shared/lib/contactNormalization": typeof shared_lib_contactNormalization;
  "shared/lib/crypto/bytesToHex": typeof shared_lib_crypto_bytesToHex;
  "shared/lib/driveValidators": typeof shared_lib_driveValidators;
  "shared/lib/email/emailDomain": typeof shared_lib_email_emailDomain;
  "shared/lib/email/emailRenders": typeof shared_lib_email_emailRenders;
  "shared/lib/email/emailSend": typeof shared_lib_email_emailSend;
  "shared/lib/listAdminPackages": typeof shared_lib_listAdminPackages;
  "shared/lib/listAdminSessions": typeof shared_lib_listAdminSessions;
  "shared/lib/rateLimits": typeof shared_lib_rateLimits;
  "shared/lib/reminderScheduleTime": typeof shared_lib_reminderScheduleTime;
  "shared/lib/result": typeof shared_lib_result;
  "shared/lib/tests/testIds": typeof shared_lib_tests_testIds;
  "shared/services/auth": typeof shared_services_auth;
  "shared/services/authPermissions": typeof shared_services_authPermissions;
  "shared/services/requirePermissionActions": typeof shared_services_requirePermissionActions;
  "stripe/checkout": typeof stripe_checkout;
  "stripe/customInvoices": typeof stripe_customInvoices;
  "stripe/editInvoices": typeof stripe_editInvoices;
  "stripe/editInvoicing": typeof stripe_editInvoicing;
  "stripe/invoiceRecords": typeof stripe_invoiceRecords;
  "stripe/invoices": typeof stripe_invoices;
  "stripe/invoicing": typeof stripe_invoicing;
  "stripe/lib/adjustmentInvoice": typeof stripe_lib_adjustmentInvoice;
  "stripe/lib/apiErrors": typeof stripe_lib_apiErrors;
  "stripe/lib/checkoutSession": typeof stripe_lib_checkoutSession;
  "stripe/lib/client": typeof stripe_lib_client;
  "stripe/lib/customInvoices": typeof stripe_lib_customInvoices;
  "stripe/lib/editInvoiceBilling": typeof stripe_lib_editInvoiceBilling;
  "stripe/lib/editInvoiceDb": typeof stripe_lib_editInvoiceDb;
  "stripe/lib/editInvoiceLineItems": typeof stripe_lib_editInvoiceLineItems;
  "stripe/lib/editInvoiceRequest": typeof stripe_lib_editInvoiceRequest;
  "stripe/lib/editInvoiceStripe": typeof stripe_lib_editInvoiceStripe;
  "stripe/lib/invoice": typeof stripe_lib_invoice;
  "stripe/lib/invoiceBillingUrls": typeof stripe_lib_invoiceBillingUrls;
  "stripe/lib/invoiceDownloads": typeof stripe_lib_invoiceDownloads;
  "stripe/lib/invoices": typeof stripe_lib_invoices;
  "stripe/services/bookingCustomInvoice": typeof stripe_services_bookingCustomInvoice;
  "stripe/services/checkoutSession": typeof stripe_services_checkoutSession;
  "stripe/services/editInvoiceBilling": typeof stripe_services_editInvoiceBilling;
  "stripe/services/editInvoiceSend": typeof stripe_services_editInvoiceSend;
  "stripe/services/editInvoiceValidators": typeof stripe_services_editInvoiceValidators;
  "stripe/services/invoiceMutations": typeof stripe_services_invoiceMutations;
  "stripe/services/invoicePayment": typeof stripe_services_invoicePayment;
  "stripe/services/invoicePdf": typeof stripe_services_invoicePdf;
  "stripe/services/invoiceSend": typeof stripe_services_invoiceSend;
  "stripe/services/invoices": typeof stripe_services_invoices;
  "tests/insertDocumentDefaults": typeof tests_insertDocumentDefaults;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  rateLimiter: import("@convex-dev/rate-limiter/_generated/component.js").ComponentApi<"rateLimiter">;
};
