/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicTermsAndConditionsRouteImport } from './routes/_public/terms-and-conditions'
import { Route as PublicPrivacyPolicyRouteImport } from './routes/_public/privacy-policy'
import { Route as PublicPricingRouteImport } from './routes/_public/pricing'
import { Route as PublicGalleryRouteImport } from './routes/_public/gallery'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicConvexRouteImport } from './routes/_public/_convex'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as PublicConvexRescheduleCompleteRouteImport } from './routes/_public/_convex/reschedule-complete'
import { Route as PublicConvexPackageCompleteRouteImport } from './routes/_public/_convex/package-complete'
import { Route as PublicConvexBookingExpiredRouteImport } from './routes/_public/_convex/booking-expired'
import { Route as PublicConvexBookingCompleteRouteImport } from './routes/_public/_convex/booking-complete'
import { Route as PublicConvexBookRouteImport } from './routes/_public/_convex/book'
import { Route as PublicConvexRescheduleTokenRouteImport } from './routes/_public/_convex/reschedule.$token'
import { Route as PublicConvexPackageScheduleTokenRouteImport } from './routes/_public/_convex/package-schedule.$token'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTermsAndConditionsRoute =
  PublicTermsAndConditionsRouteImport.update({
    id: '/terms-and-conditions',
    path: '/terms-and-conditions',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicPrivacyPolicyRoute = PublicPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPricingRoute = PublicPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGalleryRoute = PublicGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicConvexRoute = PublicConvexRouteImport.update({
  id: '/_convex',
  getParentRoute: () => PublicRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const PublicConvexRescheduleCompleteRoute =
  PublicConvexRescheduleCompleteRouteImport.update({
    id: '/reschedule-complete',
    path: '/reschedule-complete',
    getParentRoute: () => PublicConvexRoute,
  } as any)
const PublicConvexPackageCompleteRoute =
  PublicConvexPackageCompleteRouteImport.update({
    id: '/package-complete',
    path: '/package-complete',
    getParentRoute: () => PublicConvexRoute,
  } as any)
const PublicConvexBookingExpiredRoute =
  PublicConvexBookingExpiredRouteImport.update({
    id: '/booking-expired',
    path: '/booking-expired',
    getParentRoute: () => PublicConvexRoute,
  } as any)
const PublicConvexBookingCompleteRoute =
  PublicConvexBookingCompleteRouteImport.update({
    id: '/booking-complete',
    path: '/booking-complete',
    getParentRoute: () => PublicConvexRoute,
  } as any)
const PublicConvexBookRoute = PublicConvexBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => PublicConvexRoute,
} as any)
const PublicConvexRescheduleTokenRoute =
  PublicConvexRescheduleTokenRouteImport.update({
    id: '/reschedule/$token',
    path: '/reschedule/$token',
    getParentRoute: () => PublicConvexRoute,
  } as any)
const PublicConvexPackageScheduleTokenRoute =
  PublicConvexPackageScheduleTokenRouteImport.update({
    id: '/package-schedule/$token',
    path: '/package-schedule/$token',
    getParentRoute: () => PublicConvexRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof AuthDashboardRoute
  '/login': typeof AuthLoginRoute
  '/contact': typeof PublicContactRoute
  '/gallery': typeof PublicGalleryRoute
  '/pricing': typeof PublicPricingRoute
  '/privacy-policy': typeof PublicPrivacyPolicyRoute
  '/terms-and-conditions': typeof PublicTermsAndConditionsRoute
  '/book': typeof PublicConvexBookRoute
  '/booking-complete': typeof PublicConvexBookingCompleteRoute
  '/booking-expired': typeof PublicConvexBookingExpiredRoute
  '/package-complete': typeof PublicConvexPackageCompleteRoute
  '/reschedule-complete': typeof PublicConvexRescheduleCompleteRoute
  '/package-schedule/$token': typeof PublicConvexPackageScheduleTokenRoute
  '/reschedule/$token': typeof PublicConvexRescheduleTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof AuthDashboardRoute
  '/login': typeof AuthLoginRoute
  '/contact': typeof PublicContactRoute
  '/gallery': typeof PublicGalleryRoute
  '/pricing': typeof PublicPricingRoute
  '/privacy-policy': typeof PublicPrivacyPolicyRoute
  '/terms-and-conditions': typeof PublicTermsAndConditionsRoute
  '/book': typeof PublicConvexBookRoute
  '/booking-complete': typeof PublicConvexBookingCompleteRoute
  '/booking-expired': typeof PublicConvexBookingExpiredRoute
  '/package-complete': typeof PublicConvexPackageCompleteRoute
  '/reschedule-complete': typeof PublicConvexRescheduleCompleteRoute
  '/package-schedule/$token': typeof PublicConvexPackageScheduleTokenRoute
  '/reschedule/$token': typeof PublicConvexRescheduleTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_public/_convex': typeof PublicConvexRouteWithChildren
  '/_public/contact': typeof PublicContactRoute
  '/_public/gallery': typeof PublicGalleryRoute
  '/_public/pricing': typeof PublicPricingRoute
  '/_public/privacy-policy': typeof PublicPrivacyPolicyRoute
  '/_public/terms-and-conditions': typeof PublicTermsAndConditionsRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/_convex/book': typeof PublicConvexBookRoute
  '/_public/_convex/booking-complete': typeof PublicConvexBookingCompleteRoute
  '/_public/_convex/booking-expired': typeof PublicConvexBookingExpiredRoute
  '/_public/_convex/package-complete': typeof PublicConvexPackageCompleteRoute
  '/_public/_convex/reschedule-complete': typeof PublicConvexRescheduleCompleteRoute
  '/_public/_convex/package-schedule/$token': typeof PublicConvexPackageScheduleTokenRoute
  '/_public/_convex/reschedule/$token': typeof PublicConvexRescheduleTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/contact'
    | '/gallery'
    | '/pricing'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/book'
    | '/booking-complete'
    | '/booking-expired'
    | '/package-complete'
    | '/reschedule-complete'
    | '/package-schedule/$token'
    | '/reschedule/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/contact'
    | '/gallery'
    | '/pricing'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/book'
    | '/booking-complete'
    | '/booking-expired'
    | '/package-complete'
    | '/reschedule-complete'
    | '/package-schedule/$token'
    | '/reschedule/$token'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/_auth/dashboard'
    | '/_auth/login'
    | '/_public/_convex'
    | '/_public/contact'
    | '/_public/gallery'
    | '/_public/pricing'
    | '/_public/privacy-policy'
    | '/_public/terms-and-conditions'
    | '/_public/'
    | '/_public/_convex/book'
    | '/_public/_convex/booking-complete'
    | '/_public/_convex/booking-expired'
    | '/_public/_convex/package-complete'
    | '/_public/_convex/reschedule-complete'
    | '/_public/_convex/package-schedule/$token'
    | '/_public/_convex/reschedule/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/terms-and-conditions': {
      id: '/_public/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof PublicTermsAndConditionsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy-policy': {
      id: '/_public/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PublicPrivacyPolicyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/pricing': {
      id: '/_public/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PublicPricingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/gallery': {
      id: '/_public/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof PublicGalleryRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/_convex': {
      id: '/_public/_convex'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicConvexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_public/_convex/reschedule-complete': {
      id: '/_public/_convex/reschedule-complete'
      path: '/reschedule-complete'
      fullPath: '/reschedule-complete'
      preLoaderRoute: typeof PublicConvexRescheduleCompleteRouteImport
      parentRoute: typeof PublicConvexRoute
    }
    '/_public/_convex/package-complete': {
      id: '/_public/_convex/package-complete'
      path: '/package-complete'
      fullPath: '/package-complete'
      preLoaderRoute: typeof PublicConvexPackageCompleteRouteImport
      parentRoute: typeof PublicConvexRoute
    }
    '/_public/_convex/booking-expired': {
      id: '/_public/_convex/booking-expired'
      path: '/booking-expired'
      fullPath: '/booking-expired'
      preLoaderRoute: typeof PublicConvexBookingExpiredRouteImport
      parentRoute: typeof PublicConvexRoute
    }
    '/_public/_convex/booking-complete': {
      id: '/_public/_convex/booking-complete'
      path: '/booking-complete'
      fullPath: '/booking-complete'
      preLoaderRoute: typeof PublicConvexBookingCompleteRouteImport
      parentRoute: typeof PublicConvexRoute
    }
    '/_public/_convex/book': {
      id: '/_public/_convex/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof PublicConvexBookRouteImport
      parentRoute: typeof PublicConvexRoute
    }
    '/_public/_convex/reschedule/$token': {
      id: '/_public/_convex/reschedule/$token'
      path: '/reschedule/$token'
      fullPath: '/reschedule/$token'
      preLoaderRoute: typeof PublicConvexRescheduleTokenRouteImport
      parentRoute: typeof PublicConvexRoute
    }
    '/_public/_convex/package-schedule/$token': {
      id: '/_public/_convex/package-schedule/$token'
      path: '/package-schedule/$token'
      fullPath: '/package-schedule/$token'
      preLoaderRoute: typeof PublicConvexPackageScheduleTokenRouteImport
      parentRoute: typeof PublicConvexRoute
    }
  }
}

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicConvexRouteChildren {
  PublicConvexBookRoute: typeof PublicConvexBookRoute
  PublicConvexBookingCompleteRoute: typeof PublicConvexBookingCompleteRoute
  PublicConvexBookingExpiredRoute: typeof PublicConvexBookingExpiredRoute
  PublicConvexPackageCompleteRoute: typeof PublicConvexPackageCompleteRoute
  PublicConvexRescheduleCompleteRoute: typeof PublicConvexRescheduleCompleteRoute
  PublicConvexPackageScheduleTokenRoute: typeof PublicConvexPackageScheduleTokenRoute
  PublicConvexRescheduleTokenRoute: typeof PublicConvexRescheduleTokenRoute
}

const PublicConvexRouteChildren: PublicConvexRouteChildren = {
  PublicConvexBookRoute: PublicConvexBookRoute,
  PublicConvexBookingCompleteRoute: PublicConvexBookingCompleteRoute,
  PublicConvexBookingExpiredRoute: PublicConvexBookingExpiredRoute,
  PublicConvexPackageCompleteRoute: PublicConvexPackageCompleteRoute,
  PublicConvexRescheduleCompleteRoute: PublicConvexRescheduleCompleteRoute,
  PublicConvexPackageScheduleTokenRoute: PublicConvexPackageScheduleTokenRoute,
  PublicConvexRescheduleTokenRoute: PublicConvexRescheduleTokenRoute,
}

const PublicConvexRouteWithChildren = PublicConvexRoute._addFileChildren(
  PublicConvexRouteChildren,
)

interface PublicRouteChildren {
  PublicConvexRoute: typeof PublicConvexRouteWithChildren
  PublicContactRoute: typeof PublicContactRoute
  PublicGalleryRoute: typeof PublicGalleryRoute
  PublicPricingRoute: typeof PublicPricingRoute
  PublicPrivacyPolicyRoute: typeof PublicPrivacyPolicyRoute
  PublicTermsAndConditionsRoute: typeof PublicTermsAndConditionsRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicConvexRoute: PublicConvexRouteWithChildren,
  PublicContactRoute: PublicContactRoute,
  PublicGalleryRoute: PublicGalleryRoute,
  PublicPricingRoute: PublicPricingRoute,
  PublicPrivacyPolicyRoute: PublicPrivacyPolicyRoute,
  PublicTermsAndConditionsRoute: PublicTermsAndConditionsRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
